var hierarchy =
[
    [ "ad_data_type_selector_t", "structad__data__type__selector__t.html", null ],
    [ "adc_buffer_t", "structadc__buffer__t.html", null ],
    [ "adc_channel_config_result_t", "structadc__channel__config__result__t.html", null ],
    [ "adc_channel_config_t", "structadc__channel__config__t.html", null ],
    [ "adc_config_t", "structadc__config__t.html", null ],
    [ "AdcBuffer", "classAdcBuffer.html", null ],
    [ "adv_background_parsed_t", "structadv__background__parsed__t.html", null ],
    [ "adv_background_parsed_v1_t", "structadv__background__parsed__v1__t.html", null ],
    [ "adv_background_t", "structadv__background__t.html", null ],
    [ "AES", "classAES.html", null ],
    [ "asset_filter_cmd_commit_filter_changes_t", "structasset__filter__cmd__commit__filter__changes__t.html", null ],
    [ "asset_filter_cmd_get_filter_summaries_ret_t", "structasset__filter__cmd__get__filter__summaries__ret__t.html", null ],
    [ "asset_filter_cmd_remove_filter_t", "structasset__filter__cmd__remove__filter__t.html", null ],
    [ "asset_filter_cmd_upload_filter_t", "structasset__filter__cmd__upload__filter__t.html", null ],
    [ "asset_filter_flags_t", "unionasset__filter__flags__t.html", null ],
    [ "asset_filter_runtime_data_t", "structasset__filter__runtime__data__t.html", null ],
    [ "asset_filter_summary_t", "structasset__filter__summary__t.html", null ],
    [ "asset_filters_version_t", "structasset__filters__version__t.html", null ],
    [ "asset_id_t", "structasset__id__t.html", null ],
    [ "asset_record_t", "structasset__record__t.html", null ],
    [ "asset_report_uart_id_t", "structasset__report__uart__id__t.html", null ],
    [ "asset_report_uart_mac_t", "structasset__report__uart__mac__t.html", null ],
    [ "AssetAcceptedEvent", "classAssetAcceptedEvent.html", null ],
    [ "AssetFilterData", "classAssetFilterData.html", null ],
    [ "AssetFilterInput", "classAssetFilterInput.html", null ],
    [ "AssetFilterMetadata", "classAssetFilterMetadata.html", null ],
    [ "AssetFilterOutput", "classAssetFilterOutput.html", null ],
    [ "AssetHandlerMac", "classAssetHandlerMac.html", null ],
    [ "AssetHandlerShortId", "classAssetHandlerShortId.html", null ],
    [ "BaseClass< N >", "classBaseClass.html", [
      [ "State", "classState.html", null ]
    ] ],
    [ "BaseClass< 1 >", "classBaseClass.html", [
      [ "Service", "classService.html", [
        [ "CrownstoneService", "classCrownstoneService.html", [
          [ "SetupService", "classSetupService.html", null ]
        ] ],
        [ "DeviceInformationService", "classDeviceInformationService.html", null ]
      ] ]
    ] ],
    [ "BaseClass< 3 >", "classBaseClass.html", [
      [ "Stack", "classStack.html", null ]
    ] ],
    [ "Behaviour", "classBehaviour.html", [
      [ "SwitchBehaviour", "classSwitchBehaviour.html", [
        [ "ExtendedSwitchBehaviour", "classExtendedSwitchBehaviour.html", null ]
      ] ],
      [ "TwilightBehaviour", "classTwilightBehaviour.html", null ]
    ] ],
    [ "behaviour_debug_t", "structbehaviour__debug__t.html", null ],
    [ "behaviour_settings_t", "unionbehaviour__settings__t.html", null ],
    [ "BitmaskVarSize", "classBitmaskVarSize.html", null ],
    [ "ble_central_connect_t", "structble__central__connect__t.html", null ],
    [ "ble_central_discover_t", "structble__central__discover__t.html", null ],
    [ "ble_central_discovery_t", "structble__central__discovery__t.html", null ],
    [ "ble_central_notification_t", "structble__central__notification__t.html", null ],
    [ "ble_central_read_result_t", "structble__central__read__result__t.html", null ],
    [ "ble_central_read_t", "structble__central__read__t.html", null ],
    [ "ble_central_write_t", "structble__central__write__t.html", null ],
    [ "ble_connected_t", "structble__connected__t.html", null ],
    [ "BleHandler", "classBleHandler.html", null ],
    [ "boards_config_t", "structboards__config__t.html", null ],
    [ "BufferAccessor", "classBufferAccessor.html", [
      [ "ControlPacketAccessor< PAYLOAD_SIZE >", "classControlPacketAccessor.html", null ],
      [ "ResultPacketAccessor< PAYLOAD_SIZE >", "classResultPacketAccessor.html", null ]
    ] ],
    [ "CharacteristicBase", "classCharacteristicBase.html", [
      [ "CharacteristicGeneric< buffer_ptr_t >", "classCharacteristicGeneric.html", [
        [ "Characteristic< buffer_ptr_t >", "classCharacteristic_3_01buffer__ptr__t_01_4.html", null ]
      ] ],
      [ "CharacteristicGeneric< std::string >", "classCharacteristicGeneric.html", [
        [ "Characteristic< std::string >", "classCharacteristic_3_01std_1_1string_01_4.html", null ]
      ] ],
      [ "CharacteristicGeneric< uint32_t >", "classCharacteristicGeneric.html", null ],
      [ "CharacteristicGeneric< T >", "classCharacteristicGeneric.html", [
        [ "Characteristic< uint32_t >", "classCharacteristic.html", null ],
        [ "Characteristic< T, E >", "classCharacteristic.html", null ],
        [ "Characteristic< T, typename std::enable_if< std::is_arithmetic< T >::value >::type >", "classCharacteristic_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__arithmetic_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", null ]
      ] ]
    ] ],
    [ "CharacteristicBuffer", "classCharacteristicBuffer.html", [
      [ "CharacteristicReadBuffer", "classCharacteristicReadBuffer.html", null ],
      [ "CharacteristicWriteBuffer", "classCharacteristicWriteBuffer.html", null ]
    ] ],
    [ "CharacteristicInit", "structCharacteristicInit.html", null ],
    [ "CircularBuffer< T >", "classCircularBuffer.html", null ],
    [ "CircularBuffer< adc_buffer_id_t >", "classCircularBuffer.html", null ],
    [ "CircularBuffer< cs_switch_history_item_t >", "classCircularBuffer.html", null ],
    [ "CircularBuffer< int32_t >", "classCircularBuffer.html", null ],
    [ "CircularBuffer< microapp_buffered_mesh_message_t >", "classCircularBuffer.html", null ],
    [ "CircularBuffer< switch_state_t >", "classCircularBuffer.html", null ],
    [ "CircularDifferentialBuffer< T >", "classCircularDifferentialBuffer.html", null ],
    [ "cmd_source_t", "structcmd__source__t.html", null ],
    [ "cmd_source_with_counter_t", "structcmd__source__with__counter__t.html", null ],
    [ "command_adv_claim_t", "structcommand__adv__claim__t.html", null ],
    [ "command_adv_header_t", "structcommand__adv__header__t.html", null ],
    [ "COMP", "classCOMP.html", null ],
    [ "Component", "classComponent.html", [
      [ "AssetFilterStore", "classAssetFilterStore.html", null ],
      [ "AssetFilterSyncer", "classAssetFilterSyncer.html", null ],
      [ "AssetFiltering", "classAssetFiltering.html", null ],
      [ "AssetForwarder", "classAssetForwarder.html", null ],
      [ "AssetStore", "classAssetStore.html", null ],
      [ "BehaviourHandler", "classBehaviourHandler.html", null ],
      [ "BehaviourStore", "classBehaviourStore.html", null ],
      [ "Crownstone", "classCrownstone.html", null ],
      [ "NearestCrownstoneTracker", "classNearestCrownstoneTracker.html", null ],
      [ "PresenceHandler", "classPresenceHandler.html", null ],
      [ "SwitchAggregator", "classSwitchAggregator.html", null ],
      [ "TwilightHandler", "classTwilightHandler.html", null ]
    ] ],
    [ "control_command_packet_t", "structcontrol__command__packet__t.html", null ],
    [ "control_packet_header_t", "structcontrol__packet__header__t.html", null ],
    [ "control_packet_t< N >", "structcontrol__packet__t.html", null ],
    [ "control_packet_t< CS_CONTROL_PACKET_DEFAULT_PAYLOAD_SIZE >", "structcontrol__packet__t.html", null ],
    [ "conv8_16", "unionconv8__16.html", null ],
    [ "conv8_32", "unionconv8__32.html", null ],
    [ "Coroutine", "classCoroutine.html", null ],
    [ "coroutine_args_t", "structcoroutine__args__t.html", null ],
    [ "coroutine_t", "structcoroutine__t.html", null ],
    [ "CrownstoneManufacturer", "classCrownstoneManufacturer.html", null ],
    [ "cs_adc_channel_swaps_t", "structcs__adc__channel__swaps__t.html", null ],
    [ "cs_adc_restarts_t", "structcs__adc__restarts__t.html", null ],
    [ "cs_async_result_t", "structcs__async__result__t.html", null ],
    [ "cs_central_connect_t", "structcs__central__connect__t.html", null ],
    [ "cs_central_write_result_t", "structcs__central__write__result__t.html", null ],
    [ "cs_central_write_t", "structcs__central__write__t.html", null ],
    [ "cs_const_data_t", "structcs__const__data__t.html", null ],
    [ "cs_data_t", "structcs__data__t.html", null ],
    [ "cs_external_state_item_t", "structcs__external__state__item__t.html", null ],
    [ "cs_gpio_init_t", "structcs__gpio__init__t.html", null ],
    [ "cs_gpio_read_t", "structcs__gpio__read__t.html", null ],
    [ "cs_gpio_update_t", "structcs__gpio__update__t.html", null ],
    [ "cs_gpio_write_t", "structcs__gpio__write__t.html", null ],
    [ "cs_gpregret_result_t", "structcs__gpregret__result__t.html", null ],
    [ "cs_id_list_t", "structcs__id__list__t.html", null ],
    [ "cs_legacy_multi_switch_item_t", "structcs__legacy__multi__switch__item__t.html", null ],
    [ "cs_legacy_multi_switch_t", "structcs__legacy__multi__switch__t.html", null ],
    [ "cs_mesh_iv_index_t", "structcs__mesh__iv__index__t.html", null ],
    [ "cs_mesh_iv_index_v5_t", "structcs__mesh__iv__index__v5__t.html", null ],
    [ "cs_mesh_model_msg_asset_filter_version_t", "structcs__mesh__model__msg__asset__filter__version__t.html", null ],
    [ "cs_mesh_model_msg_asset_report_id_t", "structcs__mesh__model__msg__asset__report__id__t.html", null ],
    [ "cs_mesh_model_msg_asset_report_mac_t", "structcs__mesh__model__msg__asset__report__mac__t.html", null ],
    [ "cs_mesh_model_msg_ctrl_cmd_header_ext_t", "structcs__mesh__model__msg__ctrl__cmd__header__ext__t.html", null ],
    [ "cs_mesh_model_msg_ctrl_cmd_header_t", "structcs__mesh__model__msg__ctrl__cmd__header__t.html", null ],
    [ "cs_mesh_model_msg_device_heartbeat_t", "structcs__mesh__model__msg__device__heartbeat__t.html", null ],
    [ "cs_mesh_model_msg_device_list_size_t", "structcs__mesh__model__msg__device__list__size__t.html", null ],
    [ "cs_mesh_model_msg_device_register_t", "structcs__mesh__model__msg__device__register__t.html", null ],
    [ "cs_mesh_model_msg_device_token_t", "structcs__mesh__model__msg__device__token__t.html", null ],
    [ "cs_mesh_model_msg_multi_switch_item_t", "structcs__mesh__model__msg__multi__switch__item__t.html", null ],
    [ "cs_mesh_model_msg_neighbour_rssi_t", "structcs__mesh__model__msg__neighbour__rssi__t.html", null ],
    [ "cs_mesh_model_msg_profile_location_t", "structcs__mesh__model__msg__profile__location__t.html", null ],
    [ "cs_mesh_model_msg_result_header_t", "structcs__mesh__model__msg__result__header__t.html", null ],
    [ "cs_mesh_model_msg_state_0_t", "structcs__mesh__model__msg__state__0__t.html", null ],
    [ "cs_mesh_model_msg_state_1_t", "structcs__mesh__model__msg__state__1__t.html", null ],
    [ "cs_mesh_model_msg_state_header_ext_t", "structcs__mesh__model__msg__state__header__ext__t.html", null ],
    [ "cs_mesh_model_msg_state_header_t", "structcs__mesh__model__msg__state__header__t.html", null ],
    [ "cs_mesh_model_msg_stone_mac_t", "structcs__mesh__model__msg__stone__mac__t.html", null ],
    [ "cs_mesh_model_msg_sync_request_t", "structcs__mesh__model__msg__sync__request__t.html", null ],
    [ "cs_mesh_model_msg_test_t", "structcs__mesh__model__msg__test__t.html", null ],
    [ "cs_mesh_model_msg_time_sync_t", "structcs__mesh__model__msg__time__sync__t.html", null ],
    [ "cs_mesh_model_msg_time_t", "structcs__mesh__model__msg__time__t.html", null ],
    [ "cs_mesh_msg_t", "structcs__mesh__msg__t.html", null ],
    [ "MeshUtil::cs_mesh_queue_item_meta_data_t", "structMeshUtil_1_1cs__mesh__queue__item__meta__data__t.html", null ],
    [ "MeshUtil::cs_mesh_queue_item_t", "structMeshUtil_1_1cs__mesh__queue__item__t.html", null ],
    [ "MeshUtil::cs_mesh_received_msg_t", "structMeshUtil_1_1cs__mesh__received__msg__t.html", null ],
    [ "cs_mesh_seq_number_v5_t", "structcs__mesh__seq__number__v5__t.html", null ],
    [ "cs_microapp_filter_init_t", "structcs__microapp__filter__init__t.html", null ],
    [ "cs_power_samples_header_t", "structcs__power__samples__header__t.html", null ],
    [ "cs_power_samples_request_t", "structcs__power__samples__request__t.html", null ],
    [ "cs_ram_stats_t", "structcs__ram__stats__t.html", null ],
    [ "cs_result_t", "structcs__result__t.html", null ],
    [ "cs_state_data_t", "structcs__state__data__t.html", null ],
    [ "cs_state_store_queue_t", "structcs__state__store__queue__t.html", null ],
    [ "cs_switch_history_header_t", "structcs__switch__history__header__t.html", null ],
    [ "cs_switch_history_item_t", "structcs__switch__history__item__t.html", null ],
    [ "cs_twi_init_t", "structcs__twi__init__t.html", null ],
    [ "cs_twi_read_t", "structcs__twi__read__t.html", null ],
    [ "cs_twi_write_t", "structcs__twi__write__t.html", null ],
    [ "cs_type_and_id_t", "structcs__type__and__id__t.html", null ],
    [ "cs_uicr_data_t", "structcs__uicr__data__t.html", null ],
    [ "cs_uuid128_t", "structcs__uuid128__t.html", null ],
    [ "cuckoo_compressed_fingerprint_t", "structcuckoo__compressed__fingerprint__t.html", null ],
    [ "cuckoo_extended_fingerprint_t", "structcuckoo__extended__fingerprint__t.html", null ],
    [ "cuckoo_filter_data_t", "structcuckoo__filter__data__t.html", null ],
    [ "device_address_t", "structdevice__address__t.html", null ],
    [ "differential_buffer_fixed_t< T, S >", "structdifferential__buffer__fixed__t.html", null ],
    [ "differential_buffer_t< T >", "structdifferential__buffer__t.html", null ],
    [ "DifferentialBuffer< T >", "classDifferentialBuffer.html", null ],
    [ "Dimmer", "classDimmer.html", null ],
    [ "func::detail::empty_struct", "structfunc_1_1detail_1_1empty__struct.html", null ],
    [ "enable_message_payload_t", "structenable__message__payload__t.html", null ],
    [ "enable_scanner_message_payload_t", "structenable__scanner__message__payload__t.html", null ],
    [ "encryption_header_encrypted_t", "structencryption__header__encrypted__t.html", null ],
    [ "encryption_header_t", "structencryption__header__t.html", null ],
    [ "encryption_nonce_t", "structencryption__nonce__t.html", null ],
    [ "EncryptionBuffer", "classEncryptionBuffer.html", null ],
    [ "event_t", "classevent__t.html", null ],
    [ "EventDispatcher", "classEventDispatcher.html", null ],
    [ "EventListener", "classEventListener.html", [
      [ "ADC", "classADC.html", null ],
      [ "Advertiser", "classAdvertiser.html", null ],
      [ "AssetFilterStore", "classAssetFilterStore.html", null ],
      [ "AssetFilterSyncer", "classAssetFilterSyncer.html", null ],
      [ "AssetFiltering", "classAssetFiltering.html", null ],
      [ "AssetForwarder", "classAssetForwarder.html", null ],
      [ "AssetStore", "classAssetStore.html", null ],
      [ "BackgroundAdvertisementHandler", "classBackgroundAdvertisementHandler.html", null ],
      [ "BehaviourHandler", "classBehaviourHandler.html", null ],
      [ "BehaviourStore", "classBehaviourStore.html", null ],
      [ "BleCentral", "classBleCentral.html", null ],
      [ "CommandAdvHandler", "classCommandAdvHandler.html", null ],
      [ "CommandHandler", "classCommandHandler.html", null ],
      [ "ConnectionEncryption", "classConnectionEncryption.html", null ],
      [ "Crownstone", "classCrownstone.html", null ],
      [ "CrownstoneCentral", "classCrownstoneCentral.html", null ],
      [ "CrownstoneService", "classCrownstoneService.html", null ],
      [ "FactoryReset", "classFactoryReset.html", null ],
      [ "Gpio", "classGpio.html", null ],
      [ "Mesh", "classMesh.html", null ],
      [ "MeshAdvertiser", "classMeshAdvertiser.html", null ],
      [ "MeshCore", "classMeshCore.html", null ],
      [ "MeshMsgSender", "classMeshMsgSender.html", null ],
      [ "MeshTopology", "classMeshTopology.html", null ],
      [ "MeshTopologyResearch", "classMeshTopologyResearch.html", null ],
      [ "Microapp", "classMicroapp.html", null ],
      [ "MicroappCommandHandler", "classMicroappCommandHandler.html", null ],
      [ "MicroappController", "classMicroappController.html", null ],
      [ "MultiSwitchHandler", "classMultiSwitchHandler.html", null ],
      [ "NearestCrownstoneTracker", "classNearestCrownstoneTracker.html", null ],
      [ "PowerSampling", "classPowerSampling.html", null ],
      [ "PresenceHandler", "classPresenceHandler.html", null ],
      [ "SafeSwitch", "classSafeSwitch.html", null ],
      [ "Scanner", "classScanner.html", null ],
      [ "ServiceData", "classServiceData.html", null ],
      [ "Setup", "classSetup.html", null ],
      [ "SmartSwitch", "classSmartSwitch.html", null ],
      [ "State", "classState.html", null ],
      [ "SwitchAggregator", "classSwitchAggregator.html", null ],
      [ "SystemTime", "classSystemTime.html", null ],
      [ "TapToToggle", "classTapToToggle.html", null ],
      [ "TestCentral", "classTestCentral.html", null ],
      [ "TestCrownstoneCentral", "classTestCrownstoneCentral.html", null ],
      [ "TrackedDevices", "classTrackedDevices.html", null ],
      [ "Twi", "classTwi.html", null ],
      [ "TwilightHandler", "classTwilightHandler.html", null ],
      [ "UartConnection", "classUartConnection.html", null ],
      [ "UartHandler", "classUartHandler.html", null ]
    ] ],
    [ "exact_match_filter_data_t", "structexact__match__filter__data__t.html", null ],
    [ "ExternalStates", "classExternalStates.html", null ],
    [ "factory_reset_message_payload_t", "structfactory__reset__message__payload__t.html", null ],
    [ "std::false_type", null, [
      [ "func::force_function_heap_allocation< typename >", "structfunc_1_1force__function__heap__allocation.html", null ]
    ] ],
    [ "FilterInterface", "classFilterInterface.html", [
      [ "AssetFilter", "classAssetFilter.html", null ],
      [ "CuckooFilter", "classCuckooFilter.html", null ],
      [ "ExactMatchFilter", "classExactMatchFilter.html", null ]
    ] ],
    [ "func::function< typename >", "classfunc_1_1function.html", null ],
    [ "func::detail::function_manager", "structfunc_1_1detail_1_1function__manager.html", null ],
    [ "func::detail::function_manager_inplace_specialization< T, Allocator, Enable >", "structfunc_1_1detail_1_1function__manager__inplace__specialization.html", null ],
    [ "func::detail::function_manager_inplace_specialization< T, Allocator, typename std::enable_if<!is_inplace_allocated< T, Allocator >::value >::type >", "structfunc_1_1detail_1_1function__manager__inplace__specialization_3_01T_00_01Allocator_00_01typ2e5c0b756b329372e5041287ee31765b.html", null ],
    [ "func::detail::functor_padding", "structfunc_1_1detail_1_1functor__padding.html", null ],
    [ "func::detail::functor_type< T >", "structfunc_1_1detail_1_1functor__type.html", null ],
    [ "GpRegRet", "classGpRegRet.html", null ],
    [ "high_resolution_time_stamp_t", "structhigh__resolution__time__stamp__t.html", null ],
    [ "hub_data_header_t", "structhub__data__header__t.html", null ],
    [ "IBeacon", "classIBeacon.html", null ],
    [ "ibeacon_config_id_packet_t", "structibeacon__config__id__packet__t.html", null ],
    [ "internal_multi_switch_item_cmd_t", "structinternal__multi__switch__item__cmd__t.html", null ],
    [ "internal_multi_switch_item_t", "structinternal__multi__switch__item__t.html", null ],
    [ "internal_register_tracked_device_packet_t", "structinternal__register__tracked__device__packet__t.html", null ],
    [ "internal_tracked_device_heartbeat_packet_t", "structinternal__tracked__device__heartbeat__packet__t.html", null ],
    [ "CsMath::Interval< T, S >", "classCsMath_1_1Interval.html", null ],
    [ "func::detail::is_inplace_allocated< T, Allocator >", "structfunc_1_1detail_1_1is__inplace__allocated.html", null ],
    [ "func::detail::is_valid_function_argument< typename, typename >", "structfunc_1_1detail_1_1is__valid__function__argument.html", null ],
    [ "func::detail::is_valid_function_argument< function< Result(Arguments...)>, Result(Arguments...)>", "structfunc_1_1detail_1_1is__valid__function__argument_3_01function_3_01Result_07Arguments_8_8_8_cafc365df82ecf04fc46fb0becebd908.html", null ],
    [ "func::detail::is_valid_function_argument< T, Result(Arguments...)>", "structfunc_1_1detail_1_1is__valid__function__argument_3_01T_00_01Result_07Arguments_8_8_8_08_4.html", null ],
    [ "ISwitch", "classISwitch.html", null ],
    [ "KeysAndAccess", "classKeysAndAccess.html", null ],
    [ "led_message_payload_t", "structled__message__payload__t.html", null ],
    [ "Lollipop", "classLollipop.html", null ],
    [ "mac_address_t", "structmac__address__t.html", null ],
    [ "func::detail::manager_storage_type", "structfunc_1_1detail_1_1manager__storage__type.html", null ],
    [ "masked_ad_data_type_selector_t", "structmasked__ad__data__type__selector__t.html", null ],
    [ "MedianFilter", "structMedianFilter.html", null ],
    [ "MemUsageTest", "classMemUsageTest.html", null ],
    [ "mesh_control_command_packet_flags_t", "unionmesh__control__command__packet__flags__t.html", null ],
    [ "mesh_control_command_packet_header_t", "structmesh__control__command__packet__header__t.html", null ],
    [ "mesh_control_command_packet_t", "structmesh__control__command__packet__t.html", null ],
    [ "mesh_reply_t", "structmesh__reply__t.html", null ],
    [ "mesh_state_part_0_t", "structmesh__state__part__0__t.html", null ],
    [ "mesh_state_part_1_t", "structmesh__state__part__1__t.html", null ],
    [ "mesh_topo_mac_result_t", "structmesh__topo__mac__result__t.html", null ],
    [ "mesh_topology_neighbour_research_rssi_t", "structmesh__topology__neighbour__research__rssi__t.html", null ],
    [ "mesh_topology_neighbour_rssi_uart_t", "structmesh__topology__neighbour__rssi__uart__t.html", null ],
    [ "MeshModelMulticast", "classMeshModelMulticast.html", null ],
    [ "MeshModelMulticastAcked", "classMeshModelMulticastAcked.html", null ],
    [ "MeshModelMulticastNeighbours", "classMeshModelMulticastNeighbours.html", null ],
    [ "MeshModelSelector", "classMeshModelSelector.html", null ],
    [ "MeshModelUnicast", "classMeshModelUnicast.html", null ],
    [ "MeshMsgEvent", "classMeshMsgEvent.html", null ],
    [ "MeshMsgHandler", "classMeshMsgHandler.html", null ],
    [ "MeshPacketTraits< E >", "structMeshPacketTraits.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_ASSET_FILTER_VERSION >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__ASSET__FILTER__VERSION_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_ASSET_INFO_ID >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__ASSET__INFO__ID_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_ASSET_INFO_MAC >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__ASSET__INFO__MAC_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_NEIGHBOUR_RSSI >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__NEIGHBOUR__RSSI_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_RSSI_DATA >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__RSSI__DATA_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_RSSI_PING >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__RSSI__PING_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_SET_BEHAVIOUR_SETTINGS >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__SET__BEHAVIOUR__SETTINGS_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_STONE_MAC >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__STONE__MAC_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_TEST >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__TEST_01_4.html", null ],
    [ "MeshPacketTraits< CS_MESH_MODEL_TYPE_TIME_SYNC >", "structMeshPacketTraits_3_01CS__MESH__MODEL__TYPE__TIME__SYNC_01_4.html", null ],
    [ "MeshScanner", "classMeshScanner.html", null ],
    [ "microapp_advertise_request_t", "structmicroapp__advertise__request__t.html", null ],
    [ "microapp_binary_header_t", "structmicroapp__binary__header__t.html", null ],
    [ "microapp_ble_isr_t", "structmicroapp__ble__isr__t.html", null ],
    [ "microapp_buffered_mesh_message_t", "structmicroapp__buffered__mesh__message__t.html", null ],
    [ "microapp_ctrl_header_t", "structmicroapp__ctrl__header__t.html", null ],
    [ "microapp_info_t", "structmicroapp__info__t.html", null ],
    [ "microapp_pin_isr_t", "structmicroapp__pin__isr__t.html", null ],
    [ "microapp_sdk_version_t", "structmicroapp__sdk__version__t.html", null ],
    [ "microapp_state_t", "structmicroapp__state__t.html", null ],
    [ "microapp_status_t", "structmicroapp__status__t.html", null ],
    [ "microapp_upload_internal_t", "structmicroapp__upload__internal__t.html", null ],
    [ "microapp_upload_t", "structmicroapp__upload__t.html", null ],
    [ "MicroappRuntimeData", "structMicroappRuntimeData.html", null ],
    [ "MicroappStorage", "classMicroappStorage.html", null ],
    [ "multi_switch_item_t", "structmulti__switch__item__t.html", null ],
    [ "multi_switch_t", "structmulti__switch__t.html", null ],
    [ "opcode_message_payload_t", "structopcode__message__payload__t.html", null ],
    [ "pin_info_t", "structpin__info__t.html", null ],
    [ "PowerSampling::power_t", "structPowerSampling_1_1power__t.html", null ],
    [ "PresenceCondition", "classPresenceCondition.html", null ],
    [ "PresencePredicate", "classPresencePredicate.html", null ],
    [ "PresenceStateDescription", "classPresenceStateDescription.html", null ],
    [ "profile_location_t", "structprofile__location__t.html", null ],
    [ "PWM", "classPWM.html", null ],
    [ "pwm_channel_config_t", "structpwm__channel__config__t.html", null ],
    [ "pwm_config_t", "structpwm__config__t.html", null ],
    [ "RandomGenerator", "classRandomGenerator.html", null ],
    [ "RC5", "classRC5.html", null ],
    [ "RecognizeSwitch", "classRecognizeSwitch.html", null ],
    [ "register_tracked_device_packet_t", "structregister__tracked__device__packet__t.html", null ],
    [ "Relay", "classRelay.html", null ],
    [ "reset_delayed_t", "structreset__delayed__t.html", null ],
    [ "result_packet_header_t", "structresult__packet__header__t.html", null ],
    [ "result_packet_t< N >", "structresult__packet__t.html", null ],
    [ "result_packet_t< CS_RESULT_PACKET_DEFAULT_PAYLOAD_SIZE >", "structresult__packet__t.html", null ],
    [ "RNG", "classRNG.html", null ],
    [ "rssi_and_channel_float_t", "classrssi__and__channel__float__t.html", null ],
    [ "rssi_and_channel_t", "structrssi__and__channel__t.html", null ],
    [ "rssi_data_message_t", "structrssi__data__message__t.html", null ],
    [ "rssi_data_t", "structrssi__data__t.html", null ],
    [ "rssi_ping_message_t", "structrssi__ping__message__t.html", null ],
    [ "RTC", "classRTC.html", null ],
    [ "scanned_device_t", "structscanned__device__t.html", null ],
    [ "SdhStateHandler", "classSdhStateHandler.html", null ],
    [ "service_data_encrypted_alternative_state_t", "structservice__data__encrypted__alternative__state__t.html", null ],
    [ "service_data_encrypted_error_t", "structservice__data__encrypted__error__t.html", null ],
    [ "service_data_encrypted_ext_error_t", "structservice__data__encrypted__ext__error__t.html", null ],
    [ "service_data_encrypted_ext_state_t", "structservice__data__encrypted__ext__state__t.html", null ],
    [ "service_data_encrypted_microapp_t", "structservice__data__encrypted__microapp__t.html", null ],
    [ "service_data_encrypted_state_t", "structservice__data__encrypted__state__t.html", null ],
    [ "service_data_encrypted_t", "structservice__data__encrypted__t.html", null ],
    [ "service_data_hub_state_flags_t", "unionservice__data__hub__state__flags__t.html", null ],
    [ "service_data_hub_state_t", "structservice__data__hub__state__t.html", null ],
    [ "service_data_microapp_flags_t", "unionservice__data__microapp__flags__t.html", null ],
    [ "service_data_setup_state_t", "structservice__data__setup__state__t.html", null ],
    [ "service_data_setup_t", "structservice__data__setup__t.html", null ],
    [ "service_data_state_extra_flags_t", "unionservice__data__state__extra__flags__t.html", null ],
    [ "service_data_state_flags_t", "unionservice__data__state__flags__t.html", null ],
    [ "service_data_t", "unionservice__data__t.html", null ],
    [ "session_data_t", "structsession__data__t.html", null ],
    [ "set_ibeacon_config_id_packet_t", "structset__ibeacon__config__id__packet__t.html", null ],
    [ "setup_data_t", "structsetup__data__t.html", null ],
    [ "SocHandler", "classSocHandler.html", null ],
    [ "stack_buffer_fixed_t< T, S >", "structstack__buffer__fixed__t.html", null ],
    [ "stack_buffer_t< T >", "structstack__buffer__t.html", null ],
    [ "stack_params_t", "structstack__params__t.html", null ],
    [ "StackBuffer< T >", "classStackBuffer.html", null ],
    [ "Msws::State", "classMsws_1_1State.html", null ],
    [ "state_errors_t", "unionstate__errors__t.html", null ],
    [ "state_external_stone_t", "structstate__external__stone__t.html", null ],
    [ "state_packet_header_t", "structstate__packet__header__t.html", null ],
    [ "Status", "structStatus.html", null ],
    [ "Storage", "classStorage.html", null ],
    [ "Store< Rec, Size >", "classStore.html", null ],
    [ "Store< asset_record_t, MAX_RECORDS >", "classStore.html", null ],
    [ "Store< PresenceRecord, MAX_RECORDS >", "classStore.html", null ],
    [ "Store< TrackedDevice, MAX_TRACKED_DEVICES >", "classStore.html", null ],
    [ "StreamBufferAccessor", "classStreamBufferAccessor.html", null ],
    [ "sun_time_t", "structsun__time__t.html", null ],
    [ "switch_message_payload_t", "structswitch__message__payload__t.html", null ],
    [ "switch_state_t", "unionswitch__state__t.html", null ],
    [ "t2t_entry_t", "structt2t__entry__t.html", null ],
    [ "TemperatureGuard", "classTemperatureGuard.html", null ],
    [ "Time", "classTime.html", null ],
    [ "time_sync_message_t", "structtime__sync__message__t.html", null ],
    [ "TimeOfDay", "classTimeOfDay.html", null ],
    [ "Timer", "classTimer.html", null ],
    [ "tracked_device_heartbeat_packet_t", "structtracked__device__heartbeat__packet__t.html", null ],
    [ "TrackedDevice", "structTrackedDevice.html", null ],
    [ "std::true_type", null, [
      [ "std::uses_allocator< func::function< Result(Arguments...)>, Allocator >", "structstd_1_1uses__allocator_3_01func_1_1function_3_01Result_07Arguments_8_8_8_08_4_00_01Allocator_01_4.html", null ]
    ] ],
    [ "func::detail::typedeffer< Result,... >", "structfunc_1_1detail_1_1typedeffer.html", null ],
    [ "func::detail::typedeffer< Result, Argument >", "structfunc_1_1detail_1_1typedeffer_3_01Result_00_01Argument_01_4.html", null ],
    [ "func::detail::typedeffer< Result, Arguments... >", "structfunc_1_1detail_1_1typedeffer.html", [
      [ "func::function< Result(Arguments...)>", "classfunc_1_1function_3_01Result_07Arguments_8_8_8_08_4.html", null ]
    ] ],
    [ "func::detail::typedeffer< Result, First_Argument, Second_Argument >", "structfunc_1_1detail_1_1typedeffer_3_01Result_00_01First__Argument_00_01Second__Argument_01_4.html", null ],
    [ "uart_encrypted_data_header_t", "structuart__encrypted__data__header__t.html", null ],
    [ "uart_encrypted_msg_header_t", "structuart__encrypted__msg__header__t.html", null ],
    [ "uart_msg_adc_channel_config_t", "structuart__msg__adc__channel__config__t.html", null ],
    [ "uart_msg_current_t", "structuart__msg__current__t.html", null ],
    [ "uart_msg_header_t", "structuart__msg__header__t.html", null ],
    [ "uart_msg_heartbeat_t", "structuart__msg__heartbeat__t.html", null ],
    [ "uart_msg_hello_t", "structuart__msg__hello__t.html", null ],
    [ "uart_msg_hub_data_reply_header_t", "structuart__msg__hub__data__reply__header__t.html", null ],
    [ "uart_msg_log_arg_header_t", "structuart__msg__log__arg__header__t.html", null ],
    [ "uart_msg_log_array_header_t", "structuart__msg__log__array__header__t.html", null ],
    [ "uart_msg_log_common_header_t", "structuart__msg__log__common__header__t.html", null ],
    [ "uart_msg_log_header_t", "structuart__msg__log__header__t.html", null ],
    [ "uart_msg_mesh_result_packet_header_t", "structuart__msg__mesh__result__packet__header__t.html", null ],
    [ "uart_msg_power_t", "structuart__msg__power__t.html", null ],
    [ "uart_msg_session_nonce_reply_t", "structuart__msg__session__nonce__reply__t.html", null ],
    [ "uart_msg_session_nonce_t", "structuart__msg__session__nonce__t.html", null ],
    [ "uart_msg_size_header_t", "structuart__msg__size__header__t.html", null ],
    [ "uart_msg_status_reply_flags_t", "unionuart__msg__status__reply__flags__t.html", null ],
    [ "uart_msg_status_reply_t", "structuart__msg__status__reply__t.html", null ],
    [ "uart_msg_status_user_flags_t", "unionuart__msg__status__user__flags__t.html", null ],
    [ "uart_msg_status_user_t", "structuart__msg__status__user__t.html", null ],
    [ "uart_msg_tail_t", "structuart__msg__tail__t.html", null ],
    [ "uart_msg_voltage_t", "structuart__msg__voltage__t.html", null ],
    [ "uart_msg_wrapper_header_t", "structuart__msg__wrapper__header__t.html", null ],
    [ "UartCommandHandler", "classUartCommandHandler.html", null ],
    [ "UUID", "classUUID.html", null ],
    [ "VarianceAggregator", "classVarianceAggregator.html", null ],
    [ "std::vector", null, [
      [ "tuple< CharacteristicBase * >", "classtuple.html", null ],
      [ "tuple< Service * >", "classtuple.html", null ],
      [ "tuple< T >", "classtuple.html", [
        [ "fixed_tuple< Service *, MAX_SERVICE_COUNT >", "classfixed__tuple.html", null ],
        [ "fixed_tuple< T, capacity >", "classfixed__tuple.html", null ]
      ] ]
    ] ],
    [ "Watchdog", "classWatchdog.html", null ]
];