/**
 * Author: Crownstone Team
 * Copyright: Crownstone (https://crownstone.rocks)
 * Date: Aug 15, 2018
 * License: LGPLv3+, Apache License 2.0, and/or MIT (triple-licensed)
 */

#include <protocol/cs_StateTypes.h>

/*
#ifndef STRINGIFY_
#define STRINGIFY_(X) # X
#endif

char const *StateNames[] = {
	STRINGIFY_(STATE_RESET_COUNTER),
	STRINGIFY_(STATE_SWITCH_STATE),
	STRINGIFY_(STATE_ACCUMULATED_ENERGY),
	STRINGIFY_(STATE_POWER_USAGE),
	STRINGIFY_(STATE_TRACKED_DEVICES),
	STRINGIFY_(STATE_SCHEDULE),
	STRINGIFY_(STATE_OPERATION_MODE),
	STRINGIFY_(STATE_TEMPERATURE),
	STRINGIFY_(STATE_TIME),
	STRINGIFY_(STATE_FACTORY_RESET),
	STRINGIFY_(STATE_LEARNED_SWITCHES),
	STRINGIFY_(STATE_ERRORS),
	STRINGIFY_(STATE_ERROR_OVER_CURRENT),
	STRINGIFY_(STATE_ERROR_OVER_CURRENT_PWM),
	STRINGIFY_(STATE_ERROR_CHIP_TEMP),
	STRINGIFY_(STATE_ERROR_PWM_TEMP),
	STRINGIFY_(STATE_IGNORE_BITMASK),
	STRINGIFY_(STATE_IGNORE_ALL),
	STRINGIFY_(STATE_IGNORE_LOCATION),
	STRINGIFY_(STATE_ERROR_DIMMER_ON_FAILURE),
	STRINGIFY_(STATE_ERROR_DIMMER_OFF_FAILURE)
};

*/
