/**
 * Author: Crownstone Team
 * Copyright: Crownstone (https://crownstone.rocks)
 * Date: Oct 9, 2019
 * License: LGPLv3+, Apache License 2.0, and/or MIT (triple-licensed)
 */


#include<common/cs_Types.h>

CS_TYPE toCsType(uint16_t type) {

	CS_TYPE csType = static_cast<CS_TYPE>(type);
	switch(csType) {
	case CS_TYPE::CONFIG_DO_NOT_USE:
	case CS_TYPE::CONFIG_NAME:
	case CS_TYPE::CONFIG_PWM_PERIOD:
	case CS_TYPE::CONFIG_IBEACON_MAJOR:
	case CS_TYPE::CONFIG_IBEACON_MINOR:
	case CS_TYPE::CONFIG_IBEACON_UUID:
	case CS_TYPE::CONFIG_IBEACON_TXPOWER:
	case CS_TYPE::CONFIG_TX_POWER:
	case CS_TYPE::CONFIG_ADV_INTERVAL:
	case CS_TYPE::CONFIG_SCAN_DURATION:
	case CS_TYPE::CONFIG_SCAN_BREAK_DURATION:
	case CS_TYPE::CONFIG_BOOT_DELAY:
	case CS_TYPE::CONFIG_MAX_CHIP_TEMP:
	case CS_TYPE::CONFIG_CURRENT_LIMIT:
	case CS_TYPE::CONFIG_MESH_ENABLED:
	case CS_TYPE::CONFIG_ENCRYPTION_ENABLED:
	case CS_TYPE::CONFIG_IBEACON_ENABLED:
	case CS_TYPE::CONFIG_SCANNER_ENABLED:
	case CS_TYPE::CONFIG_SPHERE_ID:
	case CS_TYPE::CONFIG_CROWNSTONE_ID:
	case CS_TYPE::CONFIG_KEY_ADMIN:
	case CS_TYPE::CONFIG_KEY_MEMBER:
	case CS_TYPE::CONFIG_KEY_BASIC:
	case CS_TYPE::CONFIG_KEY_SERVICE_DATA:
	case CS_TYPE::CONFIG_MESH_DEVICE_KEY:
	case CS_TYPE::CONFIG_MESH_APP_KEY:
	case CS_TYPE::CONFIG_MESH_NET_KEY:
	case CS_TYPE::CONFIG_KEY_LOCALIZATION:
	case CS_TYPE::CONFIG_SCAN_INTERVAL:
	case CS_TYPE::CONFIG_SCAN_WINDOW:
	case CS_TYPE::CONFIG_RELAY_HIGH_DURATION:
	case CS_TYPE::CONFIG_LOW_TX_POWER:
	case CS_TYPE::CONFIG_VOLTAGE_MULTIPLIER:
	case CS_TYPE::CONFIG_CURRENT_MULTIPLIER:
	case CS_TYPE::CONFIG_VOLTAGE_ADC_ZERO:
	case CS_TYPE::CONFIG_CURRENT_ADC_ZERO:
	case CS_TYPE::CONFIG_POWER_ZERO:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN:
	case CS_TYPE::CONFIG_PWM_ALLOWED:
	case CS_TYPE::CONFIG_START_DIMMER_ON_ZERO_CROSSING:
	case CS_TYPE::CONFIG_SWITCH_LOCKED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_ENABLED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_THRESHOLD:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_ENABLED:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET:
	case CS_TYPE::CONFIG_UART_ENABLED:
	case CS_TYPE::STATE_RESET_COUNTER:
	case CS_TYPE::STATE_OPERATION_MODE:
	case CS_TYPE::STATE_SWITCH_STATE:
	case CS_TYPE::STATE_SCHEDULE:
	case CS_TYPE::STATE_ACCUMULATED_ENERGY:
	case CS_TYPE::STATE_POWER_USAGE:
	case CS_TYPE::STATE_TEMPERATURE:
	case CS_TYPE::STATE_TIME:
	case CS_TYPE::STATE_SUN_TIME:
	case CS_TYPE::STATE_FACTORY_RESET:
	case CS_TYPE::STATE_ERRORS:
	case CS_TYPE::CMD_SWITCH_OFF:
	case CS_TYPE::CMD_SWITCH_ON:
	case CS_TYPE::CMD_SWITCH_TOGGLE:
	case CS_TYPE::CMD_SWITCH:
	case CS_TYPE::CMD_MULTI_SWITCH:
	case CS_TYPE::EVT_ADV_BACKGROUND:
	case CS_TYPE::EVT_ADV_BACKGROUND_PARSED:
	case CS_TYPE::EVT_ADVERTISEMENT_UPDATED:
	case CS_TYPE::EVT_SCAN_STARTED:
	case CS_TYPE::EVT_SCAN_STOPPED:
	case CS_TYPE::EVT_DEVICE_SCANNED:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD_DIMMER:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DIMMER_ON_FAILURE_DETECTED:
	case CS_TYPE::EVT_DIMMER_OFF_FAILURE_DETECTED:
	case CS_TYPE::EVT_MESH_TIME:
	case CS_TYPE::EVT_SCHEDULE_ENTRIES_UPDATED:
	case CS_TYPE::EVT_BLE_CONNECT:
	case CS_TYPE::EVT_BLE_DISCONNECT:
	case CS_TYPE::EVT_BROWNOUT_IMPENDING:
	case CS_TYPE::EVT_SESSION_NONCE_SET:
	case CS_TYPE::EVT_KEEP_ALIVE:
	case CS_TYPE::EVT_KEEP_ALIVE_STATE:
	case CS_TYPE::EVT_DIMMER_FORCED_OFF:
	case CS_TYPE::EVT_SWITCH_FORCED_OFF:
	case CS_TYPE::EVT_RELAY_FORCED_ON:
	case CS_TYPE::EVT_CHIP_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_CHIP_TEMP_OK:
	case CS_TYPE::EVT_DIMMER_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DIMMER_TEMP_OK:
	case CS_TYPE::EVT_TICK:
	case CS_TYPE::EVT_TIME_SET:
	case CS_TYPE::EVT_DIMMER_POWERED:
	case CS_TYPE::CMD_DIMMING_ALLOWED:
	case CS_TYPE::CMD_SWITCH_LOCKED:
	case CS_TYPE::EVT_STATE_EXTERNAL_STONE:
	case CS_TYPE::EVT_STORAGE_INITIALIZED:
	case CS_TYPE::EVT_STORAGE_WRITE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_FILE_DONE:
	case CS_TYPE::EVT_STORAGE_GC_DONE:
	case CS_TYPE::EVT_STORAGE_FACTORY_RESET:
	case CS_TYPE::EVT_STORAGE_PAGES_ERASED:
	case CS_TYPE::EVT_MESH_FACTORY_RESET:
	case CS_TYPE::EVT_SETUP_DONE:
	case CS_TYPE::EVT_ADC_RESTARTED:
	case CS_TYPE::CMD_SEND_MESH_MSG:
	case CS_TYPE::CMD_SEND_MESH_MSG_KEEP_ALIVE:
	case CS_TYPE::CMD_SEND_MESH_MSG_MULTI_SWITCH:
	case CS_TYPE::CMD_SET_TIME:
	case CS_TYPE::CMD_FACTORY_RESET:
	case CS_TYPE::CMD_ENABLE_LOG_POWER:
	case CS_TYPE::CMD_ENABLE_LOG_CURRENT:
	case CS_TYPE::CMD_ENABLE_LOG_VOLTAGE:
	case CS_TYPE::CMD_ENABLE_LOG_FILTERED_CURRENT:
	case CS_TYPE::CMD_RESET_DELAYED:
	case CS_TYPE::CMD_ENABLE_ADVERTISEMENT:
	case CS_TYPE::CMD_ENABLE_MESH:
	case CS_TYPE::CMD_TOGGLE_ADC_VOLTAGE_VDD_REFERENCE_PIN:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_CURRENT:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_VOLTAGE:
	case CS_TYPE::CMD_INC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_DEC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_INC_CURRENT_RANGE:
	case CS_TYPE::CMD_DEC_CURRENT_RANGE:
	case CS_TYPE::CMD_CONTROL_CMD:
	case CS_TYPE::CMD_SET_OPERATION_MODE:
	case CS_TYPE::EVT_SAVE_BEHAVIOUR:
	case CS_TYPE::EVT_REPLACE_BEHAVIOUR:
	case CS_TYPE::EVT_REMOVE_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR_INDICES:
	case CS_TYPE::EVT_BEHAVIOURSTORE_MUTATION:
	case CS_TYPE::EVT_PRESENCE_MUTATION:
	case CS_TYPE::EVT_BEHAVIOUR_SWITCH_STATE:
	case CS_TYPE::CMD_SET_RELAY:
	case CS_TYPE::CMD_SET_DIMMER:
		return csType;
	}
	return CS_TYPE::CONFIG_DO_NOT_USE;
}

// bool validateSize(cs_state_data_t const & data, size16_t size){
// 	auto type = data.type;
// 	switch (type) {
// 		case CS_TYPE::CONFIG_BEHAVIOUR:{
// 			return Behaviour::checkSize(data.data, data.size, size);
// 		}
// 	}
// 	return size == TypeSize(type);
// }

size16_t TypeSize(CS_TYPE const & type){

	switch(type) {
	case CS_TYPE::CONFIG_DO_NOT_USE:
		return 0;
	case CS_TYPE::CONFIG_NAME:
		return MAX_STRING_STORAGE_SIZE+1;
	case CS_TYPE::CONFIG_PWM_PERIOD:
		return sizeof(TYPIFY(CONFIG_PWM_PERIOD));
	case CS_TYPE::CONFIG_IBEACON_MAJOR:
		return sizeof(TYPIFY(CONFIG_IBEACON_MAJOR));
	case CS_TYPE::CONFIG_IBEACON_MINOR:
		return sizeof(TYPIFY(CONFIG_IBEACON_MINOR));
	case CS_TYPE::CONFIG_IBEACON_UUID:
		return 16;
	case CS_TYPE::CONFIG_IBEACON_TXPOWER:
		return sizeof(TYPIFY(CONFIG_IBEACON_TXPOWER));
	case CS_TYPE::CONFIG_TX_POWER:
		return sizeof(TYPIFY(CONFIG_TX_POWER));
	case CS_TYPE::CONFIG_ADV_INTERVAL:
		return sizeof(TYPIFY(CONFIG_ADV_INTERVAL));
	case CS_TYPE::CONFIG_SCAN_DURATION:
		return sizeof(TYPIFY(CONFIG_SCAN_DURATION));
	case CS_TYPE::CONFIG_SCAN_BREAK_DURATION:
		return sizeof(TYPIFY(CONFIG_SCAN_BREAK_DURATION));
	case CS_TYPE::CONFIG_BOOT_DELAY:
		return sizeof(TYPIFY(CONFIG_BOOT_DELAY));
	case CS_TYPE::CONFIG_MAX_CHIP_TEMP:
		return sizeof(TYPIFY(CONFIG_MAX_CHIP_TEMP));
	case CS_TYPE::CONFIG_CURRENT_LIMIT:
		return 0; // Not implemented
	case CS_TYPE::CONFIG_MESH_ENABLED:
		return sizeof(TYPIFY(CONFIG_MESH_ENABLED));
	case CS_TYPE::CONFIG_ENCRYPTION_ENABLED:
		return sizeof(TYPIFY(CONFIG_ENCRYPTION_ENABLED));
	case CS_TYPE::CONFIG_IBEACON_ENABLED:
		return sizeof(TYPIFY(CONFIG_IBEACON_ENABLED));
	case CS_TYPE::CONFIG_SCANNER_ENABLED:
		return sizeof(TYPIFY(CONFIG_SCANNER_ENABLED));
	case CS_TYPE::CONFIG_SPHERE_ID:
		return sizeof(TYPIFY(CONFIG_SPHERE_ID));
	case CS_TYPE::CONFIG_CROWNSTONE_ID:
		return sizeof(TYPIFY(CONFIG_CROWNSTONE_ID));
	case CS_TYPE::CONFIG_KEY_ADMIN:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_KEY_MEMBER:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_KEY_BASIC:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_KEY_SERVICE_DATA:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_MESH_DEVICE_KEY:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_MESH_APP_KEY:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_MESH_NET_KEY:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_KEY_LOCALIZATION:
		return ENCRYPTION_KEY_LENGTH;
	case CS_TYPE::CONFIG_SCAN_INTERVAL:
		return sizeof(TYPIFY(CONFIG_SCAN_INTERVAL));
	case CS_TYPE::CONFIG_SCAN_WINDOW:
		return sizeof(TYPIFY(CONFIG_SCAN_WINDOW));
	case CS_TYPE::CONFIG_RELAY_HIGH_DURATION:
		return sizeof(TYPIFY(CONFIG_RELAY_HIGH_DURATION));
	case CS_TYPE::CONFIG_LOW_TX_POWER:
		return sizeof(TYPIFY(CONFIG_LOW_TX_POWER));
	case CS_TYPE::CONFIG_VOLTAGE_MULTIPLIER:
		return sizeof(TYPIFY(CONFIG_VOLTAGE_MULTIPLIER));
	case CS_TYPE::CONFIG_CURRENT_MULTIPLIER:
		return sizeof(TYPIFY(CONFIG_CURRENT_MULTIPLIER));
	case CS_TYPE::CONFIG_VOLTAGE_ADC_ZERO:
		return sizeof(TYPIFY(CONFIG_VOLTAGE_ADC_ZERO));
	case CS_TYPE::CONFIG_CURRENT_ADC_ZERO:
		return sizeof(TYPIFY(CONFIG_CURRENT_ADC_ZERO));
	case CS_TYPE::CONFIG_POWER_ZERO:
		return sizeof(TYPIFY(CONFIG_POWER_ZERO));
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD:
		return sizeof(TYPIFY(CONFIG_SOFT_FUSE_CURRENT_THRESHOLD));
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM:
		return sizeof(TYPIFY(CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM));
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP:
		return sizeof(TYPIFY(CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP));
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN:
		return sizeof(TYPIFY(CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN));
	case CS_TYPE::CONFIG_PWM_ALLOWED:
		return sizeof(TYPIFY(CONFIG_PWM_ALLOWED));
	case CS_TYPE::CONFIG_START_DIMMER_ON_ZERO_CROSSING:
		return sizeof(TYPIFY(CONFIG_START_DIMMER_ON_ZERO_CROSSING));
	case CS_TYPE::CONFIG_SWITCH_LOCKED:
		return sizeof(TYPIFY(CONFIG_SWITCH_LOCKED));
	case CS_TYPE::CONFIG_SWITCHCRAFT_ENABLED:
		return sizeof(TYPIFY(CONFIG_SWITCHCRAFT_ENABLED));
	case CS_TYPE::CONFIG_SWITCHCRAFT_THRESHOLD:
		return sizeof(TYPIFY(CONFIG_SWITCHCRAFT_THRESHOLD));
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_ENABLED:
		return sizeof(TYPIFY(CONFIG_TAP_TO_TOGGLE_ENABLED));
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET:
		return sizeof(TYPIFY(CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET));
	case CS_TYPE::CONFIG_UART_ENABLED:
		return sizeof(TYPIFY(CONFIG_UART_ENABLED));
	case CS_TYPE::STATE_RESET_COUNTER:
		return sizeof(TYPIFY(STATE_RESET_COUNTER));
	case CS_TYPE::STATE_SWITCH_STATE:
		return sizeof(TYPIFY(STATE_SWITCH_STATE));
	case CS_TYPE::STATE_ACCUMULATED_ENERGY:
		return sizeof(TYPIFY(STATE_ACCUMULATED_ENERGY));
	case CS_TYPE::STATE_POWER_USAGE:
		return sizeof(TYPIFY(STATE_POWER_USAGE));
	case CS_TYPE::STATE_SCHEDULE:
		return sizeof(TYPIFY(STATE_SCHEDULE));
	case CS_TYPE::STATE_OPERATION_MODE:
		return sizeof(TYPIFY(STATE_OPERATION_MODE));
	case CS_TYPE::STATE_TEMPERATURE:
		return sizeof(TYPIFY(STATE_TEMPERATURE));
	case CS_TYPE::STATE_TIME:
		return sizeof(TYPIFY(STATE_TIME));
	case CS_TYPE::STATE_SUN_TIME:
		return sizeof(TYPIFY(STATE_SUN_TIME));
	case CS_TYPE::STATE_FACTORY_RESET:
		return sizeof(TYPIFY(STATE_FACTORY_RESET));
	case CS_TYPE::STATE_ERRORS:
		return sizeof(TYPIFY(STATE_ERRORS));
	case CS_TYPE::CMD_SWITCH_OFF:
		return 0;
	case CS_TYPE::CMD_SWITCH_ON:
		return 0;
	case CS_TYPE::CMD_SWITCH_TOGGLE:
		return 0;
	case CS_TYPE::CMD_SWITCH:
		return sizeof(TYPIFY(CMD_SWITCH));
	case CS_TYPE::CMD_MULTI_SWITCH:
		return sizeof(TYPIFY(CMD_MULTI_SWITCH));
	case CS_TYPE::EVT_ADV_BACKGROUND:
		return sizeof(TYPIFY(EVT_ADV_BACKGROUND));
	case CS_TYPE::EVT_ADV_BACKGROUND_PARSED:
		return sizeof(TYPIFY(EVT_ADV_BACKGROUND_PARSED));
	case CS_TYPE::EVT_ADVERTISEMENT_UPDATED:
		return 0;
	case CS_TYPE::EVT_SCAN_STARTED:
		return 0;
	case CS_TYPE::EVT_SCAN_STOPPED:
		return 0;
	case CS_TYPE::EVT_DEVICE_SCANNED:
		return sizeof(TYPIFY(EVT_DEVICE_SCANNED));
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD_DIMMER:
		return 0;
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD:
		return 0;
	case CS_TYPE::EVT_DIMMER_ON_FAILURE_DETECTED:
		return 0;
	case CS_TYPE::EVT_DIMMER_OFF_FAILURE_DETECTED:
		return 0;
	case CS_TYPE::EVT_MESH_TIME:
		return sizeof(TYPIFY(EVT_MESH_TIME));
	case CS_TYPE::EVT_SCHEDULE_ENTRIES_UPDATED:
		return sizeof(TYPIFY(EVT_SCHEDULE_ENTRIES_UPDATED));
	case CS_TYPE::EVT_BLE_CONNECT:
		return 0;
	case CS_TYPE::EVT_BLE_DISCONNECT:
		return 0;
	case CS_TYPE::EVT_BROWNOUT_IMPENDING:
		return 0;
	case CS_TYPE::EVT_SESSION_NONCE_SET:
		return sizeof(TYPIFY(EVT_SESSION_NONCE_SET));
	case CS_TYPE::EVT_KEEP_ALIVE:
		return 0;
	case CS_TYPE::EVT_KEEP_ALIVE_STATE:
		return sizeof(TYPIFY(EVT_KEEP_ALIVE_STATE));
	case CS_TYPE::EVT_DIMMER_FORCED_OFF:
		return 0;
	case CS_TYPE::EVT_SWITCH_FORCED_OFF:
		return 0;
	case CS_TYPE::EVT_RELAY_FORCED_ON:
		return 0;
	case CS_TYPE::EVT_CHIP_TEMP_ABOVE_THRESHOLD:
		return 0;
	case CS_TYPE::EVT_CHIP_TEMP_OK:
		return 0;
	case CS_TYPE::EVT_DIMMER_TEMP_ABOVE_THRESHOLD:
		return 0;
	case CS_TYPE::EVT_DIMMER_TEMP_OK:
		return 0;
	case CS_TYPE::EVT_TICK:
		return sizeof(uint32_t);
	case CS_TYPE::EVT_TIME_SET:
		return sizeof(uint32_t);
	case CS_TYPE::EVT_DIMMER_POWERED:
		return sizeof(TYPIFY(EVT_DIMMER_POWERED));
	case CS_TYPE::CMD_DIMMING_ALLOWED:
		return sizeof(TYPIFY(CMD_DIMMING_ALLOWED));
	case CS_TYPE::CMD_SWITCH_LOCKED:
		return sizeof(TYPIFY(CMD_SWITCH_LOCKED));
	case CS_TYPE::EVT_STATE_EXTERNAL_STONE:
		return sizeof(TYPIFY(EVT_STATE_EXTERNAL_STONE));
	case CS_TYPE::EVT_STORAGE_INITIALIZED:
		return 0;
	case CS_TYPE::EVT_STORAGE_WRITE_DONE:
		return sizeof(TYPIFY(EVT_STORAGE_WRITE_DONE));
	case CS_TYPE::EVT_STORAGE_REMOVE_DONE:
		return sizeof(TYPIFY(EVT_STORAGE_REMOVE_DONE));
	case CS_TYPE::EVT_STORAGE_REMOVE_FILE_DONE:
		return sizeof(TYPIFY(EVT_STORAGE_REMOVE_FILE_DONE));
	case CS_TYPE::EVT_STORAGE_GC_DONE:
		return 0;
	case CS_TYPE::EVT_STORAGE_FACTORY_RESET:
		return 0;
	case CS_TYPE::EVT_STORAGE_PAGES_ERASED:
		return 0;
	case CS_TYPE::EVT_MESH_FACTORY_RESET:
		return 0;
	case CS_TYPE::EVT_SETUP_DONE:
		return 0;
	case CS_TYPE::EVT_ADC_RESTARTED:
		return 0;
	case CS_TYPE::CMD_ENABLE_LOG_POWER:
		return sizeof(TYPIFY(CMD_ENABLE_LOG_POWER));
	case CS_TYPE::CMD_ENABLE_LOG_CURRENT:
		return sizeof(TYPIFY(CMD_ENABLE_LOG_CURRENT));
	case CS_TYPE::CMD_ENABLE_LOG_VOLTAGE:
		return sizeof(TYPIFY(CMD_ENABLE_LOG_VOLTAGE));
	case CS_TYPE::CMD_ENABLE_LOG_FILTERED_CURRENT:
		return sizeof(TYPIFY(CMD_ENABLE_LOG_FILTERED_CURRENT));
	case CS_TYPE::CMD_RESET_DELAYED:
		return sizeof(TYPIFY(CMD_RESET_DELAYED));
	case CS_TYPE::CMD_ENABLE_ADVERTISEMENT:
		return sizeof(TYPIFY(CMD_ENABLE_ADVERTISEMENT));
	case CS_TYPE::CMD_ENABLE_MESH:
		return sizeof(TYPIFY(CMD_ENABLE_MESH));
	case CS_TYPE::CMD_TOGGLE_ADC_VOLTAGE_VDD_REFERENCE_PIN:
		return 0;
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_CURRENT:
		return sizeof(TYPIFY(CMD_ENABLE_ADC_DIFFERENTIAL_CURRENT));
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_VOLTAGE:
		return sizeof(TYPIFY(CMD_ENABLE_ADC_DIFFERENTIAL_VOLTAGE));
	case CS_TYPE::CMD_INC_VOLTAGE_RANGE:
		return 0;
	case CS_TYPE::CMD_DEC_VOLTAGE_RANGE:
		return 0;
	case CS_TYPE::CMD_INC_CURRENT_RANGE:
		return 0;
	case CS_TYPE::CMD_DEC_CURRENT_RANGE:
		return 0;
	case CS_TYPE::CMD_CONTROL_CMD:
		return sizeof(TYPIFY(CMD_CONTROL_CMD));
	case CS_TYPE::CMD_SET_OPERATION_MODE:
		return sizeof(TYPIFY(CMD_SET_OPERATION_MODE));
	case CS_TYPE::CMD_SEND_MESH_MSG:
		return sizeof(TYPIFY(CMD_SEND_MESH_MSG));
	case CS_TYPE::CMD_SEND_MESH_MSG_KEEP_ALIVE:
		return sizeof(TYPIFY(CMD_SEND_MESH_MSG_KEEP_ALIVE));
	case CS_TYPE::CMD_SEND_MESH_MSG_MULTI_SWITCH:
		return sizeof(TYPIFY(CMD_SEND_MESH_MSG_MULTI_SWITCH));
	case CS_TYPE::CMD_SET_TIME:
		return sizeof(TYPIFY(CMD_SET_TIME));
	case CS_TYPE::CMD_FACTORY_RESET:
		return 0;
	case CS_TYPE::EVT_SAVE_BEHAVIOUR:
		return sizeof(TYPIFY(EVT_SAVE_BEHAVIOUR));
	case CS_TYPE::EVT_REPLACE_BEHAVIOUR:
		return sizeof(TYPIFY(EVT_REPLACE_BEHAVIOUR));
	case CS_TYPE::EVT_REMOVE_BEHAVIOUR:
		return sizeof(TYPIFY(EVT_REMOVE_BEHAVIOUR));
	case CS_TYPE::EVT_BEHAVIOUR_SWITCH_STATE:
		return sizeof(TYPIFY(EVT_BEHAVIOUR_SWITCH_STATE));
	case CS_TYPE::EVT_GET_BEHAVIOUR:
		return sizeof(TYPIFY(EVT_GET_BEHAVIOUR));
	case CS_TYPE::EVT_GET_BEHAVIOUR_INDICES:
		return 0;
	case CS_TYPE::EVT_BEHAVIOURSTORE_MUTATION:
		return 0;
	case CS_TYPE::EVT_PRESENCE_MUTATION:
		return 0;
	case CS_TYPE::CMD_SET_RELAY:
		return sizeof(TYPIFY(CMD_SET_RELAY));
	case CS_TYPE::CMD_SET_DIMMER:
		return sizeof(TYPIFY(CMD_SET_DIMMER));	
	} // end switch

	// should never happen
	return 0;
}

const char* TypeName(CS_TYPE const & type) {

	switch(type) {
	case CS_TYPE::CONFIG_ADV_INTERVAL: return "CONFIG_ADV_INTERVAL";
	case CS_TYPE::CONFIG_BOOT_DELAY: return "CONFIG_BOOT_DELAY";
	case CS_TYPE::CONFIG_SPHERE_ID: return "CONFIG_SPHERE_ID";
	case CS_TYPE::CONFIG_CROWNSTONE_ID: return "CONFIG_CROWNSTONE_ID";
	case CS_TYPE::CONFIG_CURRENT_MULTIPLIER: return "CONFIG_CURRENT_MULTIPLIER";
	case CS_TYPE::CONFIG_CURRENT_ADC_ZERO: return "CONFIG_CURRENT_ADC_ZERO";
	case CS_TYPE::CONFIG_CURRENT_LIMIT: return "CONFIG_CURRENT_LIMIT";
	case CS_TYPE::CONFIG_DO_NOT_USE: return "CONFIG_DO_NOT_USE";
	case CS_TYPE::CONFIG_ENCRYPTION_ENABLED: return "CONFIG_ENCRYPTION_ENABLED";
	case CS_TYPE::CONFIG_IBEACON_ENABLED: return "CONFIG_IBEACON_ENABLED";
	case CS_TYPE::CONFIG_IBEACON_MAJOR: return "CONFIG_IBEACON_MAJOR";
	case CS_TYPE::CONFIG_IBEACON_MINOR: return "CONFIG_IBEACON_MINOR";
	case CS_TYPE::CONFIG_IBEACON_TXPOWER: return "CONFIG_IBEACON_TXPOWER";
	case CS_TYPE::CONFIG_IBEACON_UUID: return "CONFIG_IBEACON_UUID";
	case CS_TYPE::CONFIG_KEY_ADMIN: return "CONFIG_KEY_ADMIN";
	case CS_TYPE::CONFIG_KEY_MEMBER: return "CONFIG_KEY_MEMBER";
	case CS_TYPE::CONFIG_KEY_BASIC: return "CONFIG_KEY_BASIC";
	case CS_TYPE::CONFIG_KEY_SERVICE_DATA: return "CONFIG_KEY_SERVICE_DATA";
	case CS_TYPE::CONFIG_MESH_DEVICE_KEY: return "CONFIG_MESH_DEVICE_KEY";
	case CS_TYPE::CONFIG_MESH_APP_KEY: return "CONFIG_MESH_APP_KEY";
	case CS_TYPE::CONFIG_MESH_NET_KEY: return "CONFIG_MESH_NET_KEY";
	case CS_TYPE::CONFIG_KEY_LOCALIZATION: return "CONFIG_KEY_LOCALIZATION";
	case CS_TYPE::CONFIG_LOW_TX_POWER: return "CONFIG_LOW_TX_POWER";
	case CS_TYPE::CONFIG_MAX_CHIP_TEMP: return "CONFIG_MAX_CHIP_TEMP";
	case CS_TYPE::CONFIG_MESH_ENABLED: return "CONFIG_MESH_ENABLED";
	case CS_TYPE::CONFIG_NAME: return "CONFIG_NAME";
	case CS_TYPE::CONFIG_POWER_ZERO: return "CONFIG_POWER_ZERO";
	case CS_TYPE::CONFIG_PWM_ALLOWED: return "CONFIG_PWM_ALLOWED";
	case CS_TYPE::CONFIG_PWM_PERIOD: return "CONFIG_PWM_PERIOD";
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN: return "CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN";
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP: return "CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP";
	case CS_TYPE::CONFIG_RELAY_HIGH_DURATION: return "CONFIG_RELAY_HIGH_DURATION";
	case CS_TYPE::CONFIG_SCANNER_ENABLED: return "CONFIG_SCANNER_ENABLED";
	case CS_TYPE::CONFIG_SCAN_BREAK_DURATION: return "CONFIG_SCAN_BREAK_DURATION";
	case CS_TYPE::CONFIG_SCAN_DURATION: return "CONFIG_SCAN_DURATION";
	case CS_TYPE::CONFIG_SCAN_INTERVAL: return "CONFIG_SCAN_INTERVAL";
	case CS_TYPE::CONFIG_SCAN_WINDOW: return "CONFIG_SCAN_WINDOW";
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD: return "CONFIG_SOFT_FUSE_CURRENT_THRESHOLD";
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM: return "CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM";
	case CS_TYPE::CONFIG_SWITCHCRAFT_ENABLED: return "CONFIG_SWITCHCRAFT_ENABLED";
	case CS_TYPE::CONFIG_SWITCHCRAFT_THRESHOLD: return "CONFIG_SWITCHCRAFT_THRESHOLD";
	case CS_TYPE::CONFIG_START_DIMMER_ON_ZERO_CROSSING: return "CONFIG_START_DIMMER_ON_ZERO_CROSSING";
	case CS_TYPE::CONFIG_SWITCH_LOCKED: return "CONFIG_SWITCH_LOCKED";
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_ENABLED: return "CONFIG_TAP_TO_TOGGLE_ENABLED";
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET: return "CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET";
	case CS_TYPE::CONFIG_TX_POWER: return "CONFIG_TX_POWER";
	case CS_TYPE::CONFIG_UART_ENABLED: return "CONFIG_UART_ENABLED";
	case CS_TYPE::CONFIG_VOLTAGE_MULTIPLIER: return "CONFIG_VOLTAGE_MULTIPLIER";
	case CS_TYPE::CONFIG_VOLTAGE_ADC_ZERO: return "CONFIG_VOLTAGE_ADC_ZERO";
	case CS_TYPE::EVT_ADC_RESTARTED: return "EVT_ADC_RESTARTED";
	case CS_TYPE::EVT_ADV_BACKGROUND: return "EVT_ADV_BACKGROUND";
	case CS_TYPE::EVT_ADV_BACKGROUND_PARSED: return "EVT_ADV_BACKGROUND_PARSED";
	case CS_TYPE::EVT_ADVERTISEMENT_UPDATED: return "EVT_ADVERTISEMENT_UPDATED";
	case CS_TYPE::EVT_BLE_CONNECT: return "EVT_BLE_CONNECT";
	case CS_TYPE::EVT_BLE_DISCONNECT: return "EVT_BLE_DISCONNECT";
	case CS_TYPE::EVT_BROWNOUT_IMPENDING: return "EVT_BROWNOUT_IMPENDING";
	case CS_TYPE::EVT_CHIP_TEMP_ABOVE_THRESHOLD: return "EVT_CHIP_TEMP_ABOVE_THRESHOLD";
	case CS_TYPE::EVT_CHIP_TEMP_OK: return "EVT_CHIP_TEMP_OK";
	case CS_TYPE::CMD_RESET_DELAYED: return "EVT_CMD_RESET";
	case CS_TYPE::CMD_SET_OPERATION_MODE: return "CMD_SET_OPERATION_MODE";
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD: return "EVT_CURRENT_USAGE_ABOVE_THRESHOLD";
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD_DIMMER: return "EVT_CURRENT_USAGE_ABOVE_THRESHOLD_PWM";
	case CS_TYPE::CMD_DEC_CURRENT_RANGE: return "EVT_DEC_CURRENT_RANGE";
	case CS_TYPE::CMD_DEC_VOLTAGE_RANGE: return "EVT_DEC_VOLTAGE_RANGE";
	case CS_TYPE::EVT_DEVICE_SCANNED: return "EVT_DEVICE_SCANNED";
	case CS_TYPE::EVT_DIMMER_OFF_FAILURE_DETECTED: return "EVT_DIMMER_OFF_FAILURE_DETECTED";
	case CS_TYPE::EVT_DIMMER_ON_FAILURE_DETECTED: return "EVT_DIMMER_ON_FAILURE_DETECTED";
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_CURRENT: return "EVT_ENABLE_ADC_DIFFERENTIAL_CURRENT";
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_VOLTAGE: return "EVT_ENABLE_ADC_DIFFERENTIAL_VOLTAGE";
	case CS_TYPE::CMD_ENABLE_ADVERTISEMENT: return "EVT_ENABLE_ADVERTISEMENT";
	case CS_TYPE::CMD_ENABLE_LOG_CURRENT: return "EVT_ENABLE_LOG_CURRENT";
	case CS_TYPE::CMD_ENABLE_LOG_FILTERED_CURRENT: return "EVT_ENABLE_LOG_FILTERED_CURRENT";
	case CS_TYPE::CMD_ENABLE_LOG_POWER: return "EVT_ENABLE_LOG_POWER";
	case CS_TYPE::CMD_ENABLE_LOG_VOLTAGE: return "EVT_ENABLE_LOG_VOLTAGE";
	case CS_TYPE::CMD_ENABLE_MESH: return "EVT_ENABLE_MESH";
	case CS_TYPE::CMD_INC_CURRENT_RANGE: return "EVT_INC_CURRENT_RANGE";
	case CS_TYPE::CMD_INC_VOLTAGE_RANGE: return "EVT_INC_VOLTAGE_RANGE";
	case CS_TYPE::EVT_KEEP_ALIVE: return "EVT_KEEP_ALIVE";
	case CS_TYPE::EVT_KEEP_ALIVE_STATE: return "EVT_KEEP_ALIVE_STATE";
	case CS_TYPE::EVT_MESH_TIME: return "EVT_MESH_TIME";
	case CS_TYPE::CMD_SWITCH_OFF: return "EVT_POWER_OFF";
	case CS_TYPE::CMD_SWITCH_ON: return "EVT_POWER_ON";
	case CS_TYPE::CMD_SWITCH_TOGGLE: return "EVT_POWER_TOGGLE";
	case CS_TYPE::CMD_SWITCH: return "CMD_SWITCH";
	case CS_TYPE::CMD_MULTI_SWITCH: return "CMD_MULTI_SWITCH";
	case CS_TYPE::CMD_DIMMING_ALLOWED: return "CMD_DIMMING_ALLOWED";
	case CS_TYPE::EVT_DIMMER_FORCED_OFF: return "EVT_DIMMER_FORCED_OFF";
	case CS_TYPE::EVT_DIMMER_POWERED: return "EVT_DIMMER_POWERED";
	case CS_TYPE::EVT_DIMMER_TEMP_ABOVE_THRESHOLD: return "EVT_PWM_TEMP_ABOVE_THRESHOLD";
	case CS_TYPE::EVT_DIMMER_TEMP_OK: return "EVT_PWM_TEMP_OK";
	case CS_TYPE::EVT_RELAY_FORCED_ON: return "EVT_RELAY_FORCED_ON";
	case CS_TYPE::CMD_CONTROL_CMD: return "CMD_CONTROL_CMD";
	case CS_TYPE::EVT_SCAN_STARTED: return "EVT_SCAN_STARTED";
	case CS_TYPE::EVT_SCAN_STOPPED: return "EVT_SCAN_STOPPED";
	case CS_TYPE::EVT_SCHEDULE_ENTRIES_UPDATED: return "EVT_SCHEDULE_ENTRIES_UPDATED";
	case CS_TYPE::EVT_SESSION_NONCE_SET: return "EVT_SESSION_NONCE_SET";
	case CS_TYPE::EVT_SETUP_DONE: return "EVT_SETUP_DONE";
	case CS_TYPE::EVT_STATE_EXTERNAL_STONE: return "EVT_STATE_EXTERNAL_STONE";
	case CS_TYPE::EVT_STORAGE_INITIALIZED: return "EVT_STORAGE_INITIALIZED";
	case CS_TYPE::EVT_STORAGE_WRITE_DONE: return "EVT_STORAGE_WRITE_DONE";
	case CS_TYPE::EVT_STORAGE_REMOVE_DONE: return "EVT_STORAGE_REMOVE_DONE";
	case CS_TYPE::EVT_STORAGE_REMOVE_FILE_DONE: return "EVT_STORAGE_REMOVE_FILE_DONE";
	case CS_TYPE::EVT_STORAGE_GC_DONE: return "EVT_STORAGE_GC_DONE";
	case CS_TYPE::EVT_STORAGE_FACTORY_RESET: return "EVT_STORAGE_FACTORY_RESET";
	case CS_TYPE::EVT_STORAGE_PAGES_ERASED: return "EVT_STORAGE_PAGES_ERASED";
	case CS_TYPE::EVT_MESH_FACTORY_RESET: return "EVT_MESH_FACTORY_RESET";
	case CS_TYPE::EVT_SWITCH_FORCED_OFF: return "EVT_SWITCH_FORCED_OFF";
	case CS_TYPE::CMD_SWITCH_LOCKED: return "CMD_SWITCH_LOCKED";
	case CS_TYPE::EVT_TICK: return "EVT_TICK";
	case CS_TYPE::EVT_TIME_SET: return "EVT_TIME_SET";
	case CS_TYPE::CMD_TOGGLE_ADC_VOLTAGE_VDD_REFERENCE_PIN: return "EVT_TOGGLE_ADC_VOLTAGE_VDD_REFERENCE_PIN";
	case CS_TYPE::STATE_ACCUMULATED_ENERGY: return "STATE_ACCUMULATED_ENERGY";
	case CS_TYPE::STATE_ERRORS: return "STATE_ERRORS";
	case CS_TYPE::STATE_FACTORY_RESET: return "STATE_FACTORY_RESET";
	case CS_TYPE::STATE_OPERATION_MODE: return "STATE_OPERATION_MODE";
	case CS_TYPE::STATE_POWER_USAGE: return "STATE_POWER_USAGE";
	case CS_TYPE::STATE_RESET_COUNTER: return "STATE_RESET_COUNTER";
	case CS_TYPE::STATE_SCHEDULE: return "STATE_SCHEDULE";
	case CS_TYPE::STATE_SWITCH_STATE: return "STATE_SWITCH_STATE";
	case CS_TYPE::STATE_TEMPERATURE: return "STATE_TEMPERATURE";
	case CS_TYPE::STATE_TIME: return "STATE_TIME";
	case CS_TYPE::STATE_SUN_TIME: return "STATE_SUN_TIME";
	case CS_TYPE::CMD_SEND_MESH_MSG: return "CMD_SEND_MESH_MSG";
	case CS_TYPE::CMD_SEND_MESH_MSG_KEEP_ALIVE: return "CMD_SEND_MESH_MSG_KEEP_ALIVE";
	case CS_TYPE::CMD_SEND_MESH_MSG_MULTI_SWITCH: return "CMD_SEND_MESH_MSG_MULTI_SWITCH";
	case CS_TYPE::CMD_SET_TIME: return "CMD_SET_TIME";
	case CS_TYPE::CMD_FACTORY_RESET: return "CMD_FACTORY_RESET";
	case CS_TYPE::EVT_SAVE_BEHAVIOUR: return "EVT_SAVE_BEHAVIOUR";
	case CS_TYPE::EVT_REPLACE_BEHAVIOUR: return "EVT_REPLACE_BEHAVIOUR";
	case CS_TYPE::EVT_REMOVE_BEHAVIOUR: return "EVT_REMOVE_BEHAVIOUR";
	case CS_TYPE::EVT_GET_BEHAVIOUR: return "EVT_GET_BEHAVIOUR";
	case CS_TYPE::EVT_GET_BEHAVIOUR_INDICES: return "EVT_GET_BEHAVIOUR_INDICES";
	case CS_TYPE::EVT_BEHAVIOURSTORE_MUTATION: return "EVT_BEHAVIOURSTORE_MUTATION";
	case CS_TYPE::EVT_PRESENCE_MUTATION: return "EVT_PRESENCE_MUTATION";
	case CS_TYPE::EVT_BEHAVIOUR_SWITCH_STATE: return "EVT_BEHAVIOUR_SWITCH_STATE";
	case CS_TYPE::CMD_SET_RELAY: return "CMD_SET_RELAY";
	case CS_TYPE::CMD_SET_DIMMER: return "CMD_SET_DIMMER";
	}
	return "Unknown";
}



cs_file_id_t getFileId(CS_TYPE const & type){
	switch(type) {
	case CS_TYPE::CONFIG_NAME:
	case CS_TYPE::CONFIG_PWM_PERIOD:
	case CS_TYPE::CONFIG_IBEACON_MAJOR:
	case CS_TYPE::CONFIG_IBEACON_MINOR:
	case CS_TYPE::CONFIG_IBEACON_UUID:
	case CS_TYPE::CONFIG_IBEACON_TXPOWER:
	case CS_TYPE::CONFIG_TX_POWER:
	case CS_TYPE::CONFIG_ADV_INTERVAL:
	case CS_TYPE::CONFIG_SCAN_DURATION:
	case CS_TYPE::CONFIG_SCAN_BREAK_DURATION:
	case CS_TYPE::CONFIG_BOOT_DELAY:
	case CS_TYPE::CONFIG_MAX_CHIP_TEMP:
	case CS_TYPE::CONFIG_CURRENT_LIMIT:
	case CS_TYPE::CONFIG_MESH_ENABLED:
	case CS_TYPE::CONFIG_ENCRYPTION_ENABLED:
	case CS_TYPE::CONFIG_IBEACON_ENABLED:
	case CS_TYPE::CONFIG_SCANNER_ENABLED:
	case CS_TYPE::CONFIG_SPHERE_ID:
	case CS_TYPE::CONFIG_CROWNSTONE_ID:
	case CS_TYPE::CONFIG_KEY_ADMIN:
	case CS_TYPE::CONFIG_KEY_MEMBER:
	case CS_TYPE::CONFIG_KEY_BASIC:
	case CS_TYPE::CONFIG_KEY_SERVICE_DATA:
	case CS_TYPE::CONFIG_MESH_DEVICE_KEY:
	case CS_TYPE::CONFIG_MESH_APP_KEY:
	case CS_TYPE::CONFIG_MESH_NET_KEY:
	case CS_TYPE::CONFIG_KEY_LOCALIZATION:
	case CS_TYPE::CONFIG_SCAN_INTERVAL:
	case CS_TYPE::CONFIG_SCAN_WINDOW:
	case CS_TYPE::CONFIG_RELAY_HIGH_DURATION:
	case CS_TYPE::CONFIG_LOW_TX_POWER:
	case CS_TYPE::CONFIG_VOLTAGE_MULTIPLIER:
	case CS_TYPE::CONFIG_CURRENT_MULTIPLIER:
	case CS_TYPE::CONFIG_VOLTAGE_ADC_ZERO:
	case CS_TYPE::CONFIG_CURRENT_ADC_ZERO:
	case CS_TYPE::CONFIG_POWER_ZERO:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN:
	case CS_TYPE::CONFIG_PWM_ALLOWED:
	case CS_TYPE::CONFIG_START_DIMMER_ON_ZERO_CROSSING:
	case CS_TYPE::CONFIG_SWITCH_LOCKED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_ENABLED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_THRESHOLD:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_ENABLED:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET:
	case CS_TYPE::CONFIG_UART_ENABLED:
	case CS_TYPE::STATE_OPERATION_MODE:
	case CS_TYPE::STATE_SWITCH_STATE:
	case CS_TYPE::STATE_SCHEDULE:
		return FILE_CONFIGURATION;
	case CS_TYPE::STATE_RESET_COUNTER:
		return FILE_KEEP_FOREVER;
	case CS_TYPE::CONFIG_DO_NOT_USE:
	case CS_TYPE::STATE_ACCUMULATED_ENERGY:
	case CS_TYPE::STATE_POWER_USAGE:
	case CS_TYPE::STATE_TEMPERATURE:
	case CS_TYPE::STATE_TIME:
	case CS_TYPE::STATE_SUN_TIME:
	case CS_TYPE::STATE_FACTORY_RESET:
	case CS_TYPE::STATE_ERRORS:
	case CS_TYPE::CMD_SWITCH_OFF:
	case CS_TYPE::CMD_SWITCH_ON:
	case CS_TYPE::CMD_SWITCH_TOGGLE:
	case CS_TYPE::CMD_SWITCH:
	case CS_TYPE::CMD_MULTI_SWITCH:
	case CS_TYPE::EVT_ADV_BACKGROUND:
	case CS_TYPE::EVT_ADV_BACKGROUND_PARSED:
	case CS_TYPE::EVT_ADVERTISEMENT_UPDATED:
	case CS_TYPE::EVT_SCAN_STARTED:
	case CS_TYPE::EVT_SCAN_STOPPED:
	case CS_TYPE::EVT_DEVICE_SCANNED:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD_DIMMER:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DIMMER_ON_FAILURE_DETECTED:
	case CS_TYPE::EVT_DIMMER_OFF_FAILURE_DETECTED:
	case CS_TYPE::EVT_MESH_TIME:
	case CS_TYPE::EVT_SCHEDULE_ENTRIES_UPDATED:
	case CS_TYPE::EVT_BLE_CONNECT:
	case CS_TYPE::EVT_BLE_DISCONNECT:
	case CS_TYPE::EVT_BROWNOUT_IMPENDING:
	case CS_TYPE::EVT_SESSION_NONCE_SET:
	case CS_TYPE::EVT_KEEP_ALIVE:
	case CS_TYPE::EVT_KEEP_ALIVE_STATE:
	case CS_TYPE::EVT_DIMMER_FORCED_OFF:
	case CS_TYPE::EVT_SWITCH_FORCED_OFF:
	case CS_TYPE::EVT_RELAY_FORCED_ON:
	case CS_TYPE::EVT_CHIP_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_CHIP_TEMP_OK:
	case CS_TYPE::EVT_DIMMER_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DIMMER_TEMP_OK:
	case CS_TYPE::EVT_TICK:
	case CS_TYPE::EVT_TIME_SET:
	case CS_TYPE::EVT_DIMMER_POWERED:
	case CS_TYPE::CMD_DIMMING_ALLOWED:
	case CS_TYPE::CMD_SWITCH_LOCKED:
	case CS_TYPE::EVT_STATE_EXTERNAL_STONE:
	case CS_TYPE::EVT_STORAGE_INITIALIZED:
	case CS_TYPE::EVT_STORAGE_WRITE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_FILE_DONE:
	case CS_TYPE::EVT_STORAGE_GC_DONE:
	case CS_TYPE::EVT_STORAGE_FACTORY_RESET:
	case CS_TYPE::EVT_STORAGE_PAGES_ERASED:
	case CS_TYPE::EVT_MESH_FACTORY_RESET:
	case CS_TYPE::EVT_SETUP_DONE:
	case CS_TYPE::EVT_ADC_RESTARTED:
	case CS_TYPE::CMD_ENABLE_LOG_POWER:
	case CS_TYPE::CMD_ENABLE_LOG_CURRENT:
	case CS_TYPE::CMD_ENABLE_LOG_VOLTAGE:
	case CS_TYPE::CMD_ENABLE_LOG_FILTERED_CURRENT:
	case CS_TYPE::CMD_RESET_DELAYED:
	case CS_TYPE::CMD_ENABLE_ADVERTISEMENT:
	case CS_TYPE::CMD_ENABLE_MESH:
	case CS_TYPE::CMD_TOGGLE_ADC_VOLTAGE_VDD_REFERENCE_PIN:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_CURRENT:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_VOLTAGE:
	case CS_TYPE::CMD_INC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_DEC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_INC_CURRENT_RANGE:
	case CS_TYPE::CMD_DEC_CURRENT_RANGE:
	case CS_TYPE::CMD_CONTROL_CMD:
	case CS_TYPE::CMD_SET_OPERATION_MODE:
	case CS_TYPE::CMD_SEND_MESH_MSG:
	case CS_TYPE::CMD_SEND_MESH_MSG_KEEP_ALIVE:
	case CS_TYPE::CMD_SEND_MESH_MSG_MULTI_SWITCH:
	case CS_TYPE::CMD_SET_TIME:
	case CS_TYPE::CMD_FACTORY_RESET:
	case CS_TYPE::EVT_SAVE_BEHAVIOUR:
	case CS_TYPE::EVT_REPLACE_BEHAVIOUR:
	case CS_TYPE::EVT_REMOVE_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR_INDICES:
	case CS_TYPE::EVT_BEHAVIOURSTORE_MUTATION:
	case CS_TYPE::EVT_PRESENCE_MUTATION:
	case CS_TYPE::EVT_BEHAVIOUR_SWITCH_STATE:
	case CS_TYPE::CMD_SET_RELAY:
	case CS_TYPE::CMD_SET_DIMMER:
		return FILE_DO_NOT_USE;
	}
	// should not reach this
	return FILE_DO_NOT_USE;
}


EncryptionAccessLevel getUserAccessLevelSet(CS_TYPE const & type)  {
	switch (type) {
	case CS_TYPE::CONFIG_ADV_INTERVAL:
	case CS_TYPE::CONFIG_BOOT_DELAY:
	case CS_TYPE::CONFIG_SPHERE_ID:
	case CS_TYPE::CONFIG_CROWNSTONE_ID:
	case CS_TYPE::CONFIG_CURRENT_ADC_ZERO:
	case CS_TYPE::CONFIG_CURRENT_MULTIPLIER:
	case CS_TYPE::CONFIG_IBEACON_MAJOR:
	case CS_TYPE::CONFIG_IBEACON_MINOR:
	case CS_TYPE::CONFIG_IBEACON_UUID:
	case CS_TYPE::CONFIG_IBEACON_TXPOWER:
	case CS_TYPE::CONFIG_LOW_TX_POWER:
	case CS_TYPE::CONFIG_MAX_CHIP_TEMP:
	case CS_TYPE::CONFIG_MESH_ENABLED:
	case CS_TYPE::CONFIG_NAME:
	case CS_TYPE::CONFIG_POWER_ZERO:
	case CS_TYPE::CONFIG_PWM_ALLOWED:
	case CS_TYPE::CONFIG_PWM_PERIOD:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP:
	case CS_TYPE::CONFIG_RELAY_HIGH_DURATION:
	case CS_TYPE::CONFIG_SCAN_BREAK_DURATION:
	case CS_TYPE::CONFIG_SCAN_DURATION:
	case CS_TYPE::CONFIG_SCANNER_ENABLED:
	case CS_TYPE::CONFIG_SCAN_INTERVAL:
	case CS_TYPE::CONFIG_SCAN_WINDOW:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM:
	case CS_TYPE::CONFIG_START_DIMMER_ON_ZERO_CROSSING:
	case CS_TYPE::CONFIG_SWITCH_LOCKED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_ENABLED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_THRESHOLD:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_ENABLED:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET:
	case CS_TYPE::CONFIG_TX_POWER:
	case CS_TYPE::CONFIG_UART_ENABLED:
	case CS_TYPE::CONFIG_VOLTAGE_ADC_ZERO:
	case CS_TYPE::CONFIG_VOLTAGE_MULTIPLIER:
		return ADMIN;
	case CS_TYPE::CONFIG_CURRENT_LIMIT:
	case CS_TYPE::CONFIG_ENCRYPTION_ENABLED:
	case CS_TYPE::CONFIG_IBEACON_ENABLED:
	case CS_TYPE::CONFIG_KEY_ADMIN:
	case CS_TYPE::CONFIG_KEY_MEMBER:
	case CS_TYPE::CONFIG_KEY_BASIC:
	case CS_TYPE::CONFIG_KEY_SERVICE_DATA:
	case CS_TYPE::CONFIG_MESH_DEVICE_KEY:
	case CS_TYPE::CONFIG_MESH_APP_KEY:
	case CS_TYPE::CONFIG_MESH_NET_KEY:
	case CS_TYPE::CONFIG_KEY_LOCALIZATION:
	case CS_TYPE::CONFIG_DO_NOT_USE:
	case CS_TYPE::STATE_ACCUMULATED_ENERGY:
	case CS_TYPE::STATE_ERRORS:
	case CS_TYPE::STATE_FACTORY_RESET:
	case CS_TYPE::STATE_OPERATION_MODE:
	case CS_TYPE::STATE_POWER_USAGE:
	case CS_TYPE::STATE_RESET_COUNTER:
	case CS_TYPE::STATE_SCHEDULE:
	case CS_TYPE::STATE_SWITCH_STATE:
	case CS_TYPE::STATE_TEMPERATURE:
	case CS_TYPE::STATE_TIME:
	case CS_TYPE::STATE_SUN_TIME:
	case CS_TYPE::CMD_CONTROL_CMD:
	case CS_TYPE::CMD_DEC_CURRENT_RANGE:
	case CS_TYPE::CMD_DEC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_CURRENT:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_VOLTAGE:
	case CS_TYPE::CMD_ENABLE_ADVERTISEMENT:
	case CS_TYPE::CMD_ENABLE_LOG_CURRENT:
	case CS_TYPE::CMD_ENABLE_LOG_FILTERED_CURRENT:
	case CS_TYPE::CMD_ENABLE_LOG_POWER:
	case CS_TYPE::CMD_ENABLE_LOG_VOLTAGE:
	case CS_TYPE::CMD_ENABLE_MESH:
	case CS_TYPE::CMD_FACTORY_RESET:
	case CS_TYPE::CMD_INC_CURRENT_RANGE:
	case CS_TYPE::CMD_INC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_RESET_DELAYED:
	case CS_TYPE::CMD_SEND_MESH_MSG:
	case CS_TYPE::CMD_SEND_MESH_MSG_KEEP_ALIVE:
	case CS_TYPE::CMD_SEND_MESH_MSG_MULTI_SWITCH:
	case CS_TYPE::CMD_SET_OPERATION_MODE:
	case CS_TYPE::CMD_SET_TIME:
	case CS_TYPE::CMD_SWITCH_OFF:
	case CS_TYPE::CMD_SWITCH_ON:
	case CS_TYPE::CMD_SWITCH_TOGGLE:
	case CS_TYPE::CMD_SWITCH:
	case CS_TYPE::CMD_MULTI_SWITCH:
	case CS_TYPE::CMD_TOGGLE_ADC_VOLTAGE_VDD_REFERENCE_PIN:
	case CS_TYPE::EVT_ADC_RESTARTED:
	case CS_TYPE::EVT_ADV_BACKGROUND:
	case CS_TYPE::EVT_ADV_BACKGROUND_PARSED:
	case CS_TYPE::EVT_ADVERTISEMENT_UPDATED:
	case CS_TYPE::EVT_BLE_CONNECT:
	case CS_TYPE::EVT_BLE_DISCONNECT:
	case CS_TYPE::EVT_BROWNOUT_IMPENDING:
	case CS_TYPE::EVT_CHIP_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_CHIP_TEMP_OK:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD_DIMMER:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DEVICE_SCANNED:
	case CS_TYPE::EVT_DIMMER_FORCED_OFF:
	case CS_TYPE::EVT_DIMMER_OFF_FAILURE_DETECTED:
	case CS_TYPE::EVT_DIMMER_ON_FAILURE_DETECTED:
	case CS_TYPE::EVT_DIMMER_POWERED:
	case CS_TYPE::EVT_DIMMER_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DIMMER_TEMP_OK:
	case CS_TYPE::CMD_DIMMING_ALLOWED:
	case CS_TYPE::EVT_KEEP_ALIVE:
	case CS_TYPE::EVT_KEEP_ALIVE_STATE:
	case CS_TYPE::EVT_MESH_TIME:
	case CS_TYPE::EVT_RELAY_FORCED_ON:
	case CS_TYPE::EVT_SCAN_STARTED:
	case CS_TYPE::EVT_SCAN_STOPPED:
	case CS_TYPE::EVT_SCHEDULE_ENTRIES_UPDATED:
	case CS_TYPE::EVT_SESSION_NONCE_SET:
	case CS_TYPE::EVT_SETUP_DONE:
	case CS_TYPE::EVT_STATE_EXTERNAL_STONE:
	case CS_TYPE::EVT_STORAGE_INITIALIZED:
	case CS_TYPE::EVT_STORAGE_WRITE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_FILE_DONE:
	case CS_TYPE::EVT_STORAGE_GC_DONE:
	case CS_TYPE::EVT_STORAGE_FACTORY_RESET:
	case CS_TYPE::EVT_STORAGE_PAGES_ERASED:
	case CS_TYPE::EVT_MESH_FACTORY_RESET:
	case CS_TYPE::EVT_SWITCH_FORCED_OFF:
	case CS_TYPE::CMD_SWITCH_LOCKED:
	case CS_TYPE::EVT_TICK:
	case CS_TYPE::EVT_TIME_SET:
	case CS_TYPE::EVT_SAVE_BEHAVIOUR:
	case CS_TYPE::EVT_REPLACE_BEHAVIOUR:
	case CS_TYPE::EVT_REMOVE_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR_INDICES:
	case CS_TYPE::EVT_BEHAVIOURSTORE_MUTATION:
	case CS_TYPE::EVT_PRESENCE_MUTATION:
	case CS_TYPE::EVT_BEHAVIOUR_SWITCH_STATE:
	case CS_TYPE::CMD_SET_RELAY:
	case CS_TYPE::CMD_SET_DIMMER:
		return NO_ONE;
	}
	return NO_ONE;
}

EncryptionAccessLevel getUserAccessLevelGet(CS_TYPE const & type) {
	switch (type) {
	case CS_TYPE::CONFIG_ADV_INTERVAL:
	case CS_TYPE::CONFIG_BOOT_DELAY:
	case CS_TYPE::CONFIG_SPHERE_ID:
	case CS_TYPE::CONFIG_CROWNSTONE_ID:
	case CS_TYPE::CONFIG_CURRENT_ADC_ZERO:
	case CS_TYPE::CONFIG_CURRENT_MULTIPLIER:
	case CS_TYPE::CONFIG_ENCRYPTION_ENABLED:
	case CS_TYPE::CONFIG_IBEACON_ENABLED:
	case CS_TYPE::CONFIG_IBEACON_MAJOR:
	case CS_TYPE::CONFIG_IBEACON_MINOR:
	case CS_TYPE::CONFIG_IBEACON_UUID:
	case CS_TYPE::CONFIG_IBEACON_TXPOWER:
	case CS_TYPE::CONFIG_LOW_TX_POWER:
	case CS_TYPE::CONFIG_MAX_CHIP_TEMP:
	case CS_TYPE::CONFIG_MESH_ENABLED:
	case CS_TYPE::CONFIG_NAME:
	case CS_TYPE::CONFIG_POWER_ZERO:
	case CS_TYPE::CONFIG_PWM_ALLOWED:
	case CS_TYPE::CONFIG_PWM_PERIOD:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_DOWN:
	case CS_TYPE::CONFIG_PWM_TEMP_VOLTAGE_THRESHOLD_UP:
	case CS_TYPE::CONFIG_RELAY_HIGH_DURATION:
	case CS_TYPE::CONFIG_SCAN_BREAK_DURATION:
	case CS_TYPE::CONFIG_SCAN_DURATION:
	case CS_TYPE::CONFIG_SCANNER_ENABLED:
	case CS_TYPE::CONFIG_SCAN_INTERVAL:
	case CS_TYPE::CONFIG_SCAN_WINDOW:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD:
	case CS_TYPE::CONFIG_SOFT_FUSE_CURRENT_THRESHOLD_PWM:
	case CS_TYPE::CONFIG_START_DIMMER_ON_ZERO_CROSSING:
	case CS_TYPE::CONFIG_SWITCH_LOCKED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_ENABLED:
	case CS_TYPE::CONFIG_SWITCHCRAFT_THRESHOLD:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_ENABLED:
	case CS_TYPE::CONFIG_TAP_TO_TOGGLE_RSSI_THRESHOLD_OFFSET:
	case CS_TYPE::CONFIG_TX_POWER:
	case CS_TYPE::CONFIG_UART_ENABLED:
	case CS_TYPE::CONFIG_VOLTAGE_ADC_ZERO:
	case CS_TYPE::CONFIG_VOLTAGE_MULTIPLIER:
		return ADMIN;
	case CS_TYPE::STATE_ACCUMULATED_ENERGY:
	case CS_TYPE::STATE_ERRORS:
	case CS_TYPE::STATE_POWER_USAGE:
	case CS_TYPE::STATE_RESET_COUNTER:
	case CS_TYPE::STATE_SCHEDULE:
	case CS_TYPE::STATE_SWITCH_STATE:
	case CS_TYPE::STATE_TEMPERATURE:
	case CS_TYPE::STATE_TIME:
	case CS_TYPE::STATE_SUN_TIME:
		return MEMBER;
	case CS_TYPE::CONFIG_CURRENT_LIMIT:
	case CS_TYPE::CONFIG_KEY_ADMIN:
	case CS_TYPE::CONFIG_KEY_MEMBER:
	case CS_TYPE::CONFIG_KEY_BASIC:
	case CS_TYPE::CONFIG_KEY_SERVICE_DATA:
	case CS_TYPE::CONFIG_MESH_DEVICE_KEY:
	case CS_TYPE::CONFIG_MESH_APP_KEY:
	case CS_TYPE::CONFIG_MESH_NET_KEY:
	case CS_TYPE::CONFIG_KEY_LOCALIZATION:
	case CS_TYPE::CONFIG_DO_NOT_USE:
	case CS_TYPE::STATE_FACTORY_RESET:
	case CS_TYPE::STATE_OPERATION_MODE:
	case CS_TYPE::CMD_CONTROL_CMD:
	case CS_TYPE::CMD_DEC_CURRENT_RANGE:
	case CS_TYPE::CMD_DEC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_CURRENT:
	case CS_TYPE::CMD_ENABLE_ADC_DIFFERENTIAL_VOLTAGE:
	case CS_TYPE::CMD_ENABLE_ADVERTISEMENT:
	case CS_TYPE::CMD_ENABLE_LOG_CURRENT:
	case CS_TYPE::CMD_ENABLE_LOG_FILTERED_CURRENT:
	case CS_TYPE::CMD_ENABLE_LOG_POWER:
	case CS_TYPE::CMD_ENABLE_LOG_VOLTAGE:
	case CS_TYPE::CMD_ENABLE_MESH:
	case CS_TYPE::CMD_FACTORY_RESET:
	case CS_TYPE::CMD_INC_CURRENT_RANGE:
	case CS_TYPE::CMD_INC_VOLTAGE_RANGE:
	case CS_TYPE::CMD_RESET_DELAYED:
	case CS_TYPE::CMD_SEND_MESH_MSG:
	case CS_TYPE::CMD_SEND_MESH_MSG_KEEP_ALIVE:
	case CS_TYPE::CMD_SEND_MESH_MSG_MULTI_SWITCH:
	case CS_TYPE::CMD_SET_OPERATION_MODE:
	case CS_TYPE::CMD_SET_TIME:
	case CS_TYPE::CMD_SWITCH_OFF:
	case CS_TYPE::CMD_SWITCH_ON:
	case CS_TYPE::CMD_SWITCH_TOGGLE:
	case CS_TYPE::CMD_SWITCH:
	case CS_TYPE::CMD_MULTI_SWITCH:
	case CS_TYPE::CMD_TOGGLE_ADC_VOLTAGE_VDD_REFERENCE_PIN:
	case CS_TYPE::EVT_ADC_RESTARTED:
	case CS_TYPE::EVT_ADV_BACKGROUND:
	case CS_TYPE::EVT_ADV_BACKGROUND_PARSED:
	case CS_TYPE::EVT_ADVERTISEMENT_UPDATED:
	case CS_TYPE::EVT_BLE_CONNECT:
	case CS_TYPE::EVT_BLE_DISCONNECT:
	case CS_TYPE::EVT_BROWNOUT_IMPENDING:
	case CS_TYPE::EVT_CHIP_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_CHIP_TEMP_OK:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD_DIMMER:
	case CS_TYPE::EVT_CURRENT_USAGE_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DEVICE_SCANNED:
	case CS_TYPE::EVT_DIMMER_FORCED_OFF:
	case CS_TYPE::EVT_DIMMER_OFF_FAILURE_DETECTED:
	case CS_TYPE::EVT_DIMMER_ON_FAILURE_DETECTED:
	case CS_TYPE::EVT_DIMMER_POWERED:
	case CS_TYPE::EVT_DIMMER_TEMP_ABOVE_THRESHOLD:
	case CS_TYPE::EVT_DIMMER_TEMP_OK:
	case CS_TYPE::CMD_DIMMING_ALLOWED:
	case CS_TYPE::EVT_KEEP_ALIVE:
	case CS_TYPE::EVT_KEEP_ALIVE_STATE:
	case CS_TYPE::EVT_MESH_TIME:
	case CS_TYPE::EVT_RELAY_FORCED_ON:
	case CS_TYPE::EVT_SCAN_STARTED:
	case CS_TYPE::EVT_SCAN_STOPPED:
	case CS_TYPE::EVT_SCHEDULE_ENTRIES_UPDATED:
	case CS_TYPE::EVT_SESSION_NONCE_SET:
	case CS_TYPE::EVT_SETUP_DONE:
	case CS_TYPE::EVT_STATE_EXTERNAL_STONE:
	case CS_TYPE::EVT_STORAGE_INITIALIZED:
	case CS_TYPE::EVT_STORAGE_WRITE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_DONE:
	case CS_TYPE::EVT_STORAGE_REMOVE_FILE_DONE:
	case CS_TYPE::EVT_STORAGE_GC_DONE:
	case CS_TYPE::EVT_STORAGE_FACTORY_RESET:
	case CS_TYPE::EVT_STORAGE_PAGES_ERASED:
	case CS_TYPE::EVT_MESH_FACTORY_RESET:
	case CS_TYPE::EVT_SWITCH_FORCED_OFF:
	case CS_TYPE::CMD_SWITCH_LOCKED:
	case CS_TYPE::EVT_TICK:
	case CS_TYPE::EVT_TIME_SET:
	case CS_TYPE::EVT_SAVE_BEHAVIOUR:
	case CS_TYPE::EVT_REPLACE_BEHAVIOUR:
	case CS_TYPE::EVT_REMOVE_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR:
	case CS_TYPE::EVT_GET_BEHAVIOUR_INDICES:
	case CS_TYPE::EVT_BEHAVIOURSTORE_MUTATION:
	case CS_TYPE::EVT_PRESENCE_MUTATION:
	case CS_TYPE::EVT_BEHAVIOUR_SWITCH_STATE:
	case CS_TYPE::CMD_SET_RELAY:
	case CS_TYPE::CMD_SET_DIMMER:
		return NO_ONE;
	}
	return NO_ONE;
}
