function(get_versions WORKING_DIRECTORY FIRMWARE_VERSION BOOTLOADER_VERSION)
  # Note, these commands are Linux only. Check for other OS how to retrieve this info
  execute_process(COMMAND sed -n "2p" "${WORKING_DIRECTORY}/VERSION" OUTPUT_VARIABLE LOCAL_FIRMWARE_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE) 
  execute_process(COMMAND sed -n "2p" "${WORKING_DIRECTORY}/bootloader/VERSION" OUTPUT_VARIABLE LOCAL_BOOTLOADER_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  #message(STATUS "Firmware version: ${LOCAL_FIRMWARE_VERSION}")
  #message(STATUS "Bootloader version: ${LOCAL_BOOTLOADER_VERSION}")
  set(${FIRMWARE_VERSION} "${LOCAL_FIRMWARE_VERSION}" PARENT_SCOPE)
  set(${BOOTLOADER_VERSION} "${LOCAL_BOOTLOADER_VERSION}" PARENT_SCOPE)
endfunction()

