/**
 * Author: Dominik Egger
 * Copyright: Distributed Organisms B.V. (DoBots)
 * Date: Oct 21, 2016
 * License: LGPLv3+
 */
#pragma once

#include <cfg/cs_Boards.h>

#if (HARDWARE_BOARD==PCA10001)
#define HARDWARE_VERSION_STRING "PCA10001"
#endif
#if (HARDWARE_BOARD==NRF6310)
#define HARDWARE_VERSION_STRING "NRF6310"
#endif
#if (HARDWARE_BOARD==CROWNSTONE)
#define HARDWARE_VERSION_STRING "crownstone"
#endif
#if (HARDWARE_BOARD==VIRTUALMEMO)
#define HARDWARE_VERSION_STRING "VIRTUALMEMO"
#endif
#if (HARDWARE_BOARD==CROWNSTONE2)
#define HARDWARE_VERSION_STRING "crownstone_v0.86"
#endif
#if (HARDWARE_BOARD==PCA10000)
#define HARDWARE_VERSION_STRING "PCA10000"
#endif
#if (HARDWARE_BOARD==PCA10031)
#define HARDWARE_VERSION_STRING "PCA10031"
#endif
#if (HARDWARE_BOARD==CROWNSTONE3)
#define HARDWARE_VERSION_STRING "crownstone_v0.90"
#endif
#if (HARDWARE_BOARD==CROWNSTONE4)
#define HARDWARE_VERSION_STRING "crownstone_v0.92"
#endif
#if (HARDWARE_BOARD==NORDIC_BEACON)
#define HARDWARE_VERSION_STRING "NORDIC_BEACON"
#endif
#if (HARDWARE_BOARD==DOBEACON)
#define HARDWARE_VERSION_STRING "dobeacon_v0.7"
#endif
#if (HARDWARE_BOARD==CROWNSTONE5)
#define HARDWARE_VERSION_STRING "plugin_quant"
#endif
#if (HARDWARE_BOARD==DOBEACON2)
#define HARDWARE_VERSION_STRING "dobeacon_v?"
#endif
#if (HARDWARE_BOARD==PCA10036)
#define HARDWARE_VERSION_STRING "PCA10036"
#endif
#if (HARDWARE_BOARD==PCA10040)
#define HARDWARE_VERSION_STRING "PCA10040"
#endif
#if (HARDWARE_BOARD==BUILTIN_ACR01B1A)
#define HARDWARE_VERSION_STRING "builtin_ACR01B1A"
#endif
#if (HARDWARE_BOARD==PLUGIN_FLEXPRINT_01)
#define HARDWARE_VERSION_STRING "plugin_flexprint_01"
#endif
#if (HARDWARE_BOARD==CS_PLUG_0)
#define HARDWARE_VERSION_STRING "crownstone"
#endif
#if (HARDWARE_BOARD==CS_PLUG_0_86_0)
#define HARDWARE_VERSION_STRING "crownstone_v0.86"
#endif
#if (HARDWARE_BOARD==CS_PLUG_0_90_0)
#define HARDWARE_VERSION_STRING "crownstone_v0.90"
#endif
#if (HARDWARE_BOARD==CS_PLUG_0_92_0)
#define HARDWARE_VERSION_STRING "crownstone_v0.92"
#endif
#if (HARDWARE_BOARD==CS_PLUG_QUANT)
#define HARDWARE_VERSION_STRING "plugin_quant"
#endif
#if (HARDWARE_BOARD==CS_PLUG_FLEXPRINT_01)
#define HARDWARE_VERSION_STRING "plugin_flexprint_01"
#endif
#if (HARDWARE_BOARD==CS_BUILT_ACR01B1A)
#define HARDWARE_VERSION_STRING "builtin_ACR01B1A"
#endif
#if (HARDWARE_BOARD==GS_PLUG_0_07_0)
#define HARDWARE_VERSION_STRING "dobeacon_v0.7"
#endif
#if (HARDWARE_BOARD==GS_PLUG_)
#define HARDWARE_VERSION_STRING "dobeacon_v?"
#endif
#if (HARDWARE_BOARD==GS_EU_CHINA_1_0_0)
#define HARDWARE_VERSION_STRING "guidestone_china_1.0"
#endif

#ifndef HARDWARE_VERSION_STRING
#error "Add HARDWARE_VERSION_STRING to cfg/cs_HardwareVersions.h"
#endif

