#!/bin/bash

path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $path/_utils.sh

export BLUENET_WORKSPACE_DIR="$path/../.."
export BLUENET_CONFIG_DIR="$BLUENET_WORKSPACE_DIR/config"
export BLUENET_SOURCE_DIR="$BLUENET_WORKSPACE_DIR/source"
export BLUENET_BUILD_DIR="$BLUENET_WORKSPACE_DIR/build"
export BLUENET_BIN_DIR="$BLUENET_WORKSPACE_DIR/bin"
export BLUENET_RELEASE_DIR="$BLUENET_WORKSPACE_DIR/release"


cs_info "BLUENET_WORKSPACE_DIR is ${BLUENET_WORKSPACE_DIR}"
cs_info "BLUENET_CONFIG_DIR is ${BLUENET_CONFIG_DIR}"
cs_info "BLUENET_BUILD_DIR is ${BLUENET_BUILD_DIR}"
cs_info "BLUENET_BIN_DIR is ${BLUENET_BIN_DIR}"
cs_info "BLUENET_RELEASE_DIR is ${BLUENET_RELEASE_DIR}"
